packages:
  - frontend
  - server
  - packages/*

nodeLinker: hoisted
packageImportMethod: copy
injectWorkspacePackages: true
dedupeInjectedDeps: false

allowBuilds:
  '@google/genai': false
  esbuild: true
  protobufjs: false
