"""Moonshot (Kimi) model data provider."""

from __future__ import annotations

from app.model_info.schemas import ModelCapabilities, ModelDetail

MODELS: dict[str, ModelDetail] = {
    "moonshot-v1-8k": ModelDetail(
        id="moonshot-v1-8k",
        name="Moonshot V1 8K",
        description="月之暗面 Kimi 模型，8K 上下文版本。",
        vendor_id="moonshot",
        input_context_window=8_192,
        max_output_tokens=4_096,
        suggested_max_tokens=4_096,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        model_family="moonshot-v1",
    ),
    "moonshot-v1-32k": ModelDetail(
        id="moonshot-v1-32k",
        name="Moonshot V1 32K",
        description="月之暗面 Kimi 模型，32K 上下文版本。",
        vendor_id="moonshot",
        input_context_window=32_768,
        max_output_tokens=8_192,
        suggested_max_tokens=8_192,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        model_family="moonshot-v1",
    ),
    "moonshot-v1-128k": ModelDetail(
        id="moonshot-v1-128k",
        name="Moonshot V1 128K",
        description="月之暗面 Kimi 模型，128K 上下文版本，适合长文档分析。",
        vendor_id="moonshot",
        input_context_window=131_072,
        max_output_tokens=8_192,
        suggested_max_tokens=8_192,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        model_family="moonshot-v1",
    ),
    "kimi-k3": ModelDetail(
        id="kimi-k3",
        name="Kimi K3",
        description="Kimi 旗舰模型，1M 上下文，原生支持视觉理解，面向软件工程与深度推理。",
        vendor_id="moonshot",
        input_context_window=1_048_576,
        max_output_tokens=131_072,
        suggested_max_tokens=32_768,
        capabilities=ModelCapabilities(text=True, image=True, video=True, audio=False),
        pricing_input_per_1m=3,
        pricing_output_per_1m=15,
        recommended=True,
        model_family="kimi",
    ),
    "kimi-k2.7-code": ModelDetail(
        id="kimi-k2.7-code",
        name="Kimi K2.7 Code",
        description="Kimi 编程模型，256K 上下文，长上下文指令遵循更可靠。",
        vendor_id="moonshot",
        input_context_window=262_144,
        max_output_tokens=262_144,
        suggested_max_tokens=32_768,
        capabilities=ModelCapabilities(text=True, image=True, video=True, audio=False),
        pricing_input_per_1m=0.95,
        pricing_output_per_1m=4,
        model_family="kimi",
    ),
    "kimi-k2.7-code-highspeed": ModelDetail(
        id="kimi-k2.7-code-highspeed",
        name="Kimi K2.7 Code HighSpeed",
        description="Kimi K2.7 Code 高速版，输出约 180 Tokens/s。",
        vendor_id="moonshot",
        input_context_window=262_144,
        max_output_tokens=262_144,
        suggested_max_tokens=32_768,
        capabilities=ModelCapabilities(text=True, image=True, video=True, audio=False),
        pricing_input_per_1m=1.9,
        pricing_output_per_1m=8,
        model_family="kimi",
    ),
    "kimi-k2.6": ModelDetail(
        id="kimi-k2.6",
        name="Kimi K2.6",
        description="Kimi 通用模型，256K 上下文，支持思考与非思考模式。",
        vendor_id="moonshot",
        input_context_window=262_144,
        max_output_tokens=262_144,
        suggested_max_tokens=32_768,
        capabilities=ModelCapabilities(text=True, image=True, video=True, audio=False),
        pricing_input_per_1m=0.95,
        pricing_output_per_1m=4,
        model_family="kimi",
    ),
    "kimi-k2.5": ModelDetail(
        id="kimi-k2.5",
        name="Kimi K2.5",
        description="Kimi 多模态模型，256K 上下文（2026-08-31 起停止服务）。",
        vendor_id="moonshot",
        input_context_window=262_144,
        max_output_tokens=262_144,
        suggested_max_tokens=32_768,
        capabilities=ModelCapabilities(text=True, image=True, video=True, audio=False),
        pricing_input_per_1m=0.6,
        pricing_output_per_1m=3,
        model_family="kimi",
    ),
}


def register(target: dict[str, ModelDetail]) -> None:
    """Merge Moonshot (Kimi) models into the target repository dictionary."""
    target.update(MODELS)
