"""OpenAI model data provider."""

from __future__ import annotations

from app.model_info.schemas import ModelCapabilities, ModelDetail

MODELS: dict[str, ModelDetail] = {
    "gpt-4o": ModelDetail(
        id="gpt-4o",
        name="GPT-4o",
        description="OpenAI 多模态旗舰模型，支持图片、音频输入。",
        vendor_id="openai",
        input_context_window=128_000,
        max_output_tokens=16_384,
        suggested_max_tokens=16_384,
        capabilities=ModelCapabilities(text=True, image=True, video=False, audio=False),
        knowledge_cutoff="2023-10",
        pricing_input_per_1m=2.5,
        pricing_output_per_1m=10,
        model_family="gpt-4o",
    ),
    "gpt-4o-mini": ModelDetail(
        id="gpt-4o-mini",
        name="GPT-4o Mini",
        description="GPT-4o 轻量版，性价比优秀，适合日常任务。",
        vendor_id="openai",
        input_context_window=128_000,
        max_output_tokens=16_384,
        suggested_max_tokens=16_384,
        capabilities=ModelCapabilities(text=True, image=True, video=False, audio=False),
        knowledge_cutoff="2023-10",
        pricing_input_per_1m=0.15,
        pricing_output_per_1m=0.6,
        model_family="gpt-4o",
    ),
    "gpt-4-turbo": ModelDetail(
        id="gpt-4-turbo",
        name="GPT-4 Turbo",
        description="OpenAI GPT-4 Turbo 模型，支持 128K 上下文。",
        vendor_id="openai",
        input_context_window=128_000,
        max_output_tokens=4_096,
        suggested_max_tokens=4_096,
        capabilities=ModelCapabilities(text=True, image=True, video=False, audio=False),
        knowledge_cutoff="2023-12",
        pricing_input_per_1m=10,
        pricing_output_per_1m=30,
        model_family="gpt-4",
    ),
    "gpt-4": ModelDetail(
        id="gpt-4",
        name="GPT-4",
        description="OpenAI GPT-4 基础模型，稳定可靠（已弃用）。",
        vendor_id="openai",
        input_context_window=8_192,
        max_output_tokens=8_192,
        suggested_max_tokens=4_096,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        knowledge_cutoff="2023-09",
        pricing_input_per_1m=30,
        pricing_output_per_1m=60,
        model_family="gpt-4",
    ),
    "gpt-4.1": ModelDetail(
        id="gpt-4.1",
        name="GPT-4.1",
        description="GPT-4.1 智能非推理模型，1M 上下文。",
        vendor_id="openai",
        input_context_window=1_047_576,
        max_output_tokens=32_768,
        suggested_max_tokens=32_768,
        capabilities=ModelCapabilities(text=True, image=True, video=False, audio=False),
        pricing_input_per_1m=2,
        pricing_output_per_1m=8,
        model_family="gpt-4",
    ),
    "gpt-4.1-mini": ModelDetail(
        id="gpt-4.1-mini",
        name="GPT-4.1 Mini",
        description="GPT-4.1 轻量版，更小更快。",
        vendor_id="openai",
        input_context_window=1_047_576,
        max_output_tokens=32_768,
        suggested_max_tokens=32_768,
        capabilities=ModelCapabilities(text=True, image=True, video=False, audio=False),
        pricing_input_per_1m=0.4,
        pricing_output_per_1m=1.6,
        model_family="gpt-4",
    ),
    "gpt-4.1-nano": ModelDetail(
        id="gpt-4.1-nano",
        name="GPT-4.1 Nano",
        description="GPT-4.1 最快速、最具成本效益的版本。",
        vendor_id="openai",
        input_context_window=1_047_576,
        max_output_tokens=32_768,
        suggested_max_tokens=32_768,
        capabilities=ModelCapabilities(text=True, image=True, video=False, audio=False),
        pricing_input_per_1m=0.1,
        pricing_output_per_1m=0.4,
        model_family="gpt-4",
    ),
    "o1": ModelDetail(
        id="o1",
        name="o1",
        description="OpenAI o1 推理模型，擅长复杂数学、科学推理（已弃用）。",
        vendor_id="openai",
        input_context_window=200_000,
        max_output_tokens=100_000,
        suggested_max_tokens=32_768,
        capabilities=ModelCapabilities(text=True, image=True, video=False, audio=False),
        knowledge_cutoff="2023-10",
        pricing_input_per_1m=15,
        pricing_output_per_1m=60,
        model_family="o1",
    ),
    "o3": ModelDetail(
        id="o3",
        name="o3",
        description="OpenAI o3 推理模型，用于复杂任务。",
        vendor_id="openai",
        input_context_window=200_000,
        max_output_tokens=100_000,
        suggested_max_tokens=32_768,
        capabilities=ModelCapabilities(text=True, image=True, video=False, audio=False),
        pricing_input_per_1m=2,
        pricing_output_per_1m=8,
        model_family="o3",
    ),
    "o3-mini": ModelDetail(
        id="o3-mini",
        name="o3 Mini",
        description="OpenAI o3 轻量推理模型，支持可调推理力度（已弃用）。",
        vendor_id="openai",
        input_context_window=200_000,
        max_output_tokens=100_000,
        suggested_max_tokens=32_768,
        capabilities=ModelCapabilities(text=True, image=True, video=False, audio=False),
        knowledge_cutoff="2023-10",
        pricing_input_per_1m=1.1,
        pricing_output_per_1m=4.4,
        model_family="o3",
    ),
    "o3-pro": ModelDetail(
        id="o3-pro",
        name="o3 Pro",
        description="o3 高算力版本，产生更好响应。",
        vendor_id="openai",
        input_context_window=200_000,
        max_output_tokens=100_000,
        suggested_max_tokens=32_768,
        capabilities=ModelCapabilities(text=True, image=True, video=False, audio=False),
        pricing_input_per_1m=20,
        pricing_output_per_1m=80,
        model_family="o3",
    ),
    "o4-mini": ModelDetail(
        id="o4-mini",
        name="o4 Mini",
        description="快速、经济的推理模型（已弃用，建议使用 GPT-5 mini）。",
        vendor_id="openai",
        input_context_window=200_000,
        max_output_tokens=100_000,
        suggested_max_tokens=32_768,
        capabilities=ModelCapabilities(text=True, image=True, video=False, audio=False),
        pricing_input_per_1m=1.1,
        pricing_output_per_1m=4.4,
        model_family="o3",
    ),
    "gpt-5": ModelDetail(
        id="gpt-5",
        name="GPT-5",
        description="GPT-5 智能推理模型，支持可配置推理力度。",
        vendor_id="openai",
        input_context_window=400_000,
        max_output_tokens=128_000,
        suggested_max_tokens=32_768,
        capabilities=ModelCapabilities(text=True, image=True, video=False, audio=False),
        pricing_input_per_1m=1.25,
        pricing_output_per_1m=10,
        model_family="gpt-5",
    ),
    "gpt-5-mini": ModelDetail(
        id="gpt-5-mini",
        name="GPT-5 Mini",
        description="接近前沿智能的经济型模型，低延迟高吞吐。",
        vendor_id="openai",
        input_context_window=400_000,
        max_output_tokens=128_000,
        suggested_max_tokens=32_768,
        capabilities=ModelCapabilities(text=True, image=True, video=False, audio=False),
        pricing_input_per_1m=0.25,
        pricing_output_per_1m=2,
        model_family="gpt-5",
    ),
    "gpt-5-nano": ModelDetail(
        id="gpt-5-nano",
        name="GPT-5 Nano",
        description="最快、最具成本效益的 GPT-5 版本。",
        vendor_id="openai",
        input_context_window=400_000,
        max_output_tokens=128_000,
        suggested_max_tokens=32_768,
        capabilities=ModelCapabilities(text=True, image=True, video=False, audio=False),
        pricing_input_per_1m=0.05,
        pricing_output_per_1m=0.4,
        model_family="gpt-5",
    ),
    "gpt-5-pro": ModelDetail(
        id="gpt-5-pro",
        name="GPT-5 Pro",
        description="GPT-5 高算力版本，产生更精准的响应。",
        vendor_id="openai",
        input_context_window=400_000,
        max_output_tokens=272_000,
        suggested_max_tokens=32_768,
        capabilities=ModelCapabilities(text=True, image=True, video=False, audio=False),
        pricing_input_per_1m=15,
        pricing_output_per_1m=120,
        model_family="gpt-5",
    ),
    "gpt-5.1": ModelDetail(
        id="gpt-5.1",
        name="GPT-5.1",
        description="GPT-5.1 编码与智能体任务最佳模型，支持可配置推理力度。",
        vendor_id="openai",
        input_context_window=400_000,
        max_output_tokens=128_000,
        suggested_max_tokens=32_768,
        capabilities=ModelCapabilities(text=True, image=True, video=False, audio=False),
        pricing_input_per_1m=1.25,
        pricing_output_per_1m=10,
        model_family="gpt-5",
    ),
    "gpt-5.2": ModelDetail(
        id="gpt-5.2",
        name="GPT-5.2",
        description="上一代旗舰模型，支持可配置推理力度。",
        vendor_id="openai",
        input_context_window=400_000,
        max_output_tokens=128_000,
        suggested_max_tokens=32_768,
        capabilities=ModelCapabilities(text=True, image=True, video=False, audio=False),
        pricing_input_per_1m=1.75,
        pricing_output_per_1m=14,
        model_family="gpt-5",
    ),
    "gpt-5.2-pro": ModelDetail(
        id="gpt-5.2-pro",
        name="GPT-5.2 Pro",
        description="GPT-5.2 高算力版本，产生更精准的响应。",
        vendor_id="openai",
        input_context_window=400_000,
        max_output_tokens=128_000,
        suggested_max_tokens=32_768,
        capabilities=ModelCapabilities(text=True, image=True, video=False, audio=False),
        pricing_input_per_1m=21,
        pricing_output_per_1m=168,
        model_family="gpt-5",
    ),
    "gpt-5.3-codex": ModelDetail(
        id="gpt-5.3-codex",
        name="GPT-5.3 Codex",
        description="最强大的智能体编码模型。",
        vendor_id="openai",
        input_context_window=400_000,
        max_output_tokens=128_000,
        suggested_max_tokens=32_768,
        capabilities=ModelCapabilities(text=True, image=True, video=False, audio=False),
        pricing_input_per_1m=1.75,
        pricing_output_per_1m=14,
        model_family="gpt-5",
    ),
    "gpt-5.4": ModelDetail(
        id="gpt-5.4",
        name="GPT-5.4",
        description="面向编码与专业工作的平价模型。",
        vendor_id="openai",
        input_context_window=1_050_000,
        max_output_tokens=128_000,
        suggested_max_tokens=32_768,
        capabilities=ModelCapabilities(text=True, image=True, video=False, audio=False),
        pricing_input_per_1m=2.5,
        pricing_output_per_1m=15,
        model_family="gpt-5",
    ),
    "gpt-5.4-pro": ModelDetail(
        id="gpt-5.4-pro",
        name="GPT-5.4 Pro",
        description="GPT-5.4 高算力版本，产生更精准的响应。",
        vendor_id="openai",
        input_context_window=1_050_000,
        max_output_tokens=128_000,
        suggested_max_tokens=32_768,
        capabilities=ModelCapabilities(text=True, image=True, video=False, audio=False),
        pricing_input_per_1m=30,
        pricing_output_per_1m=180,
        model_family="gpt-5",
    ),
    "gpt-5.4-mini": ModelDetail(
        id="gpt-5.4-mini",
        name="GPT-5.4 Mini",
        description="最强的 mini 模型，适合编码、Computer Use 与子代理。",
        vendor_id="openai",
        input_context_window=400_000,
        max_output_tokens=128_000,
        suggested_max_tokens=32_768,
        capabilities=ModelCapabilities(text=True, image=True, video=False, audio=False),
        pricing_input_per_1m=0.75,
        pricing_output_per_1m=4.5,
        model_family="gpt-5",
    ),
    "gpt-5.4-nano": ModelDetail(
        id="gpt-5.4-nano",
        name="GPT-5.4 Nano",
        description="最便宜的 GPT-5.4 级模型，适合高吞吐简单任务。",
        vendor_id="openai",
        input_context_window=400_000,
        max_output_tokens=128_000,
        suggested_max_tokens=32_768,
        capabilities=ModelCapabilities(text=True, image=True, video=False, audio=False),
        pricing_input_per_1m=0.2,
        pricing_output_per_1m=1.25,
        model_family="gpt-5",
    ),
    "gpt-5.5": ModelDetail(
        id="gpt-5.5",
        name="GPT-5.5",
        description="GPT-5.5 前沿模型，适用于最复杂的专业工作。",
        vendor_id="openai",
        input_context_window=1_050_000,
        max_output_tokens=128_000,
        suggested_max_tokens=32_768,
        capabilities=ModelCapabilities(text=True, image=True, video=False, audio=False),
        knowledge_cutoff="2025-12",
        pricing_input_per_1m=5,
        pricing_output_per_1m=30,
        model_family="gpt-5",
    ),
    "gpt-5.5-pro": ModelDetail(
        id="gpt-5.5-pro",
        name="GPT-5.5 Pro",
        description="GPT-5.5 高算力版本，产生更精准的响应。",
        vendor_id="openai",
        input_context_window=1_050_000,
        max_output_tokens=128_000,
        suggested_max_tokens=32_768,
        capabilities=ModelCapabilities(text=True, image=True, video=False, audio=False),
        knowledge_cutoff="2025-12",
        pricing_input_per_1m=30,
        pricing_output_per_1m=180,
        model_family="gpt-5",
    ),
    "gpt-5.6": ModelDetail(
        id="gpt-5.6",
        name="GPT-5.6",
        description="GPT-5.6 旗舰模型别名（指向 GPT-5.6 Sol）。",
        vendor_id="openai",
        input_context_window=1_050_000,
        max_output_tokens=128_000,
        suggested_max_tokens=32_768,
        capabilities=ModelCapabilities(text=True, image=True, video=False, audio=False),
        knowledge_cutoff="2026-02",
        pricing_input_per_1m=5,
        pricing_output_per_1m=30,
        model_family="gpt-5",
    ),
    "gpt-5.6-luna": ModelDetail(
        id="gpt-5.6-luna",
        name="GPT-5.6 Luna",
        description="GPT-5.6 经济型模型，面向高吞吐成本敏感场景。",
        vendor_id="openai",
        input_context_window=1_050_000,
        max_output_tokens=128_000,
        suggested_max_tokens=32_768,
        capabilities=ModelCapabilities(text=True, image=True, video=False, audio=False),
        knowledge_cutoff="2026-02",
        pricing_input_per_1m=0.2,
        pricing_output_per_1m=1.2,
        model_family="gpt-5",
    ),
    "gpt-5.6-terra": ModelDetail(
        id="gpt-5.6-terra",
        name="GPT-5.6 Terra",
        description="GPT-5.6 平衡智能与成本的模型。",
        vendor_id="openai",
        input_context_window=1_050_000,
        max_output_tokens=128_000,
        suggested_max_tokens=32_768,
        capabilities=ModelCapabilities(text=True, image=True, video=False, audio=False),
        knowledge_cutoff="2026-02",
        pricing_input_per_1m=2,
        pricing_output_per_1m=12,
        model_family="gpt-5",
    ),
    "gpt-5.6-sol": ModelDetail(
        id="gpt-5.6-sol",
        name="GPT-5.6 Sol",
        description="GPT-5.6 旗舰模型，适用于复杂推理与编码。",
        vendor_id="openai",
        input_context_window=1_050_000,
        max_output_tokens=128_000,
        suggested_max_tokens=32_768,
        capabilities=ModelCapabilities(text=True, image=True, video=False, audio=False),
        knowledge_cutoff="2026-02",
        pricing_input_per_1m=5,
        pricing_output_per_1m=30,
        recommended=True,
        model_family="gpt-5",
    ),
}


def register(target: dict[str, ModelDetail]) -> None:
    """Merge OpenAI models into the target repository dictionary."""
    target.update(MODELS)
