"""OpenAI model data provider."""

from __future__ import annotations

from app.model_info.schemas import ModelCapabilities, ModelDetail

MODELS: dict[str, ModelDetail] = {
    "gpt-4o": ModelDetail(
        id="gpt-4o",
        name="GPT-4o",
        description="OpenAI 最新多模态旗舰模型，支持图片、音频输入。",
        vendor_id="openai",
        input_context_window=128_000,
        max_output_tokens=16_384,
        suggested_max_tokens=16_384,
        capabilities=ModelCapabilities(text=True, image=True, audio=True),
        knowledge_cutoff="2024-10",
        pricing_input_per_1m=2.50,
        pricing_output_per_1m=10.00,
        recommended=True,
        model_family="gpt-4o",
        function_calling=True,
        supports_streaming=True,
    ),
    "gpt-4o-mini": ModelDetail(
        id="gpt-4o-mini",
        name="GPT-4o Mini",
        description="GPT-4o 轻量版，性价比优秀，适合日常任务。",
        vendor_id="openai",
        input_context_window=128_000,
        max_output_tokens=16_384,
        suggested_max_tokens=16_384,
        capabilities=ModelCapabilities(text=True, image=True),
        knowledge_cutoff="2024-10",
        pricing_input_per_1m=0.15,
        pricing_output_per_1m=0.60,
        model_family="gpt-4o",
        function_calling=True,
        supports_streaming=True,
    ),
    "gpt-4-turbo": ModelDetail(
        id="gpt-4-turbo",
        name="GPT-4 Turbo",
        description="OpenAI GPT-4 Turbo 模型，支持 128K 上下文。",
        vendor_id="openai",
        input_context_window=128_000,
        max_output_tokens=4_096,
        suggested_max_tokens=4_096,
        capabilities=ModelCapabilities(text=True),
        knowledge_cutoff="2024-04",
        pricing_input_per_1m=10.00,
        pricing_output_per_1m=30.00,
        model_family="gpt-4",
        function_calling=True,
        supports_streaming=True,
    ),
    "gpt-4": ModelDetail(
        id="gpt-4",
        name="GPT-4",
        description="OpenAI GPT-4 基础模型，稳定可靠。",
        vendor_id="openai",
        input_context_window=8_192,
        max_output_tokens=4_096,
        suggested_max_tokens=4_096,
        capabilities=ModelCapabilities(text=True),
        knowledge_cutoff="2023-09",
        pricing_input_per_1m=30.00,
        pricing_output_per_1m=60.00,
        model_family="gpt-4",
        function_calling=True,
        supports_streaming=True,
    ),
    "o1": ModelDetail(
        id="o1",
        name="o1",
        description="OpenAI o1 推理模型，擅长复杂数学、科学推理。",
        vendor_id="openai",
        input_context_window=200_000,
        max_output_tokens=100_000,
        suggested_max_tokens=100_000,
        capabilities=ModelCapabilities(text=True),
        knowledge_cutoff="2023-10",
        pricing_input_per_1m=15.00,
        pricing_output_per_1m=60.00,
        model_family="o1",
        function_calling=True,
        supports_streaming=False,
    ),
    "o3-mini": ModelDetail(
        id="o3-mini",
        name="o3 Mini",
        description="OpenAI o3 轻量推理模型，支持可调推理努力。",
        vendor_id="openai",
        input_context_window=200_000,
        max_output_tokens=100_000,
        suggested_max_tokens=100_000,
        capabilities=ModelCapabilities(text=True),
        knowledge_cutoff="2024-06",
        pricing_input_per_1m=1.10,
        pricing_output_per_1m=4.40,
        model_family="o3",
        function_calling=True,
        supports_streaming=False,
    ),
    # -- GPT-5.5 --
    "gpt-5.5": ModelDetail(
        id="gpt-5.5",
        name="GPT-5.5",
        description="OpenAI GPT-5.5 最新文本模型，支持超长上下文与多模态输入。",
        vendor_id="openai",
        input_context_window=256_000,
        max_output_tokens=32_768,
        suggested_max_tokens=32_768,
        capabilities=ModelCapabilities(text=True, image=True, audio=True),
        knowledge_cutoff="2026-06",
        recommended=True,
        model_family="gpt-4o",
        function_calling=True,
        supports_streaming=True,
    ),
    # -- GPT-5.6 --
    "gpt-5.6": ModelDetail(
        id="gpt-5.6",
        name="GPT-5.6",
        description="OpenAI GPT-5.6 增强版，更强推理能力与多模态支持。",
        vendor_id="openai",
        input_context_window=256_000,
        max_output_tokens=64_000,
        suggested_max_tokens=64_000,
        capabilities=ModelCapabilities(text=True, image=True, audio=True),
        knowledge_cutoff="2026-07",
        recommended=True,
        model_family="gpt-4o",
        function_calling=True,
        supports_streaming=True,
    ),

}


def register(target: dict[str, ModelDetail]) -> None:
    """Merge OpenAI models into the target repository dictionary."""
    target.update(MODELS)
