"""Qwen/DashScope model data - auto-generated from catalog."""
from __future__ import annotations

from app.model_info.schemas import ModelCapabilities, ModelDetail

MODELS: dict[str, ModelDetail] = {
    "baichuan3-turbo": ModelDetail(
        id="baichuan3-turbo",
        name="百川3 Turbo",
        description="百川智能轻量快速模型，适合日常对话",
        vendor_id="dashscope",
        input_context_window=32768,
        max_output_tokens=4096,
        suggested_max_tokens=4096,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "baichuan4": ModelDetail(
        id="baichuan4",
        name="百川4",
        description="百川智能最新旗舰模型，支持 32K 上下文",
        vendor_id="dashscope",
        input_context_window=32768,
        max_output_tokens=4096,
        suggested_max_tokens=4096,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        recommended=True,
        model_family="qwen",
    ),
    "deepseek-chat": ModelDetail(
        id="deepseek-chat",
        name="DeepSeek Chat",
        description="DeepSeek V4 对话模型，支持 1M 上下文窗口",
        vendor_id="dashscope",
        input_context_window=1000000,
        max_output_tokens=8192,
        suggested_max_tokens=8192,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        knowledge_cutoff="2025-05",
        recommended=True,
        model_family="deepseek",
    ),
    "deepseek-r1": ModelDetail(
        id="deepseek-r1",
        name="DeepSeek R1",
        description="DeepSeek R1 推理模型，擅长复杂数学、逻辑推理",
        vendor_id="dashscope",
        input_context_window=1000000,
        max_output_tokens=8192,
        suggested_max_tokens=8192,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        knowledge_cutoff="2025-05",
        recommended=False,
        model_family="deepseek",
    ),
    "deepseek-reasoner": ModelDetail(
        id="deepseek-reasoner",
        name="DeepSeek Reasoner",
        description="DeepSeek R1 推理模型，擅长复杂推理任务",
        vendor_id="dashscope",
        input_context_window=1000000,
        max_output_tokens=8192,
        suggested_max_tokens=8192,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        knowledge_cutoff="2025-05",
        recommended=False,
        model_family="deepseek",
    ),
    "deepseek-v3": ModelDetail(
        id="deepseek-v3",
        name="DeepSeek V3",
        description="DeepSeek V3 对话模型，支持 1M 上下文窗口",
        vendor_id="dashscope",
        input_context_window=1000000,
        max_output_tokens=8192,
        suggested_max_tokens=8192,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        knowledge_cutoff="2025-05",
        recommended=False,
        model_family="deepseek",
    ),
    "glm-4-flash": ModelDetail(
        id="glm-4-flash",
        name="GLM-4 Flash",
        description="智谱 AI GLM-4 轻量快速模型，响应速度快",
        vendor_id="dashscope",
        input_context_window=128000,
        max_output_tokens=4096,
        suggested_max_tokens=4096,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "glm-4-plus": ModelDetail(
        id="glm-4-plus",
        name="GLM-4 Plus",
        description="智谱 AI GLM-4 旗舰模型，支持 128K 上下文",
        vendor_id="dashscope",
        input_context_window=128000,
        max_output_tokens=8192,
        suggested_max_tokens=8192,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        recommended=True,
        model_family="qwen",
    ),
    "glm-4v-plus": ModelDetail(
        id="glm-4v-plus",
        name="GLM-4V Plus",
        description="智谱 AI GLM-4V 多模态模型，支持图片理解",
        vendor_id="dashscope",
        input_context_window=128000,
        max_output_tokens=4096,
        suggested_max_tokens=4096,
        capabilities=ModelCapabilities(text=True, image=True, video=False, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "gpt-4-turbo": ModelDetail(
        id="gpt-4-turbo",
        name="GPT-4 Turbo",
        description="OpenAI GPT-4 Turbo 模型，支持 128K 上下文",
        vendor_id="dashscope",
        input_context_window=128000,
        max_output_tokens=4096,
        suggested_max_tokens=4096,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        knowledge_cutoff="2024-04",
        recommended=False,
        model_family="qwen",
    ),
    "gpt-4o": ModelDetail(
        id="gpt-4o",
        name="GPT-4o",
        description="OpenAI 最新多模态旗舰模型，支持图片、音频输入",
        vendor_id="dashscope",
        input_context_window=128000,
        max_output_tokens=16384,
        suggested_max_tokens=16384,
        capabilities=ModelCapabilities(text=True, image=True, video=False, audio=True),
        knowledge_cutoff="2024-10",
        recommended=True,
        model_family="qwen",
    ),
    "gpt-4o-mini": ModelDetail(
        id="gpt-4o-mini",
        name="GPT-4o Mini",
        description="GPT-4o 轻量版，性价比优秀，适合日常任务",
        vendor_id="dashscope",
        input_context_window=128000,
        max_output_tokens=16384,
        suggested_max_tokens=16384,
        capabilities=ModelCapabilities(text=True, image=True, video=False, audio=False),
        knowledge_cutoff="2024-10",
        recommended=False,
        model_family="qwen",
    ),
    "moonshot-v1-128k": ModelDetail(
        id="moonshot-v1-128k",
        name="Moonshot V1 128K",
        description="月之暗面 Kimi 模型，128K 上下文版本，适合长文档分析",
        vendor_id="dashscope",
        input_context_window=131072,
        max_output_tokens=8192,
        suggested_max_tokens=8192,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "moonshot-v1-32k": ModelDetail(
        id="moonshot-v1-32k",
        name="Moonshot V1 32K",
        description="月之暗面 Kimi 模型，32K 上下文版本",
        vendor_id="dashscope",
        input_context_window=32768,
        max_output_tokens=8192,
        suggested_max_tokens=8192,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "moonshot-v1-8k": ModelDetail(
        id="moonshot-v1-8k",
        name="Moonshot V1 8K",
        description="月之暗面 Kimi 模型，8K 上下文版本",
        vendor_id="dashscope",
        input_context_window=8192,
        max_output_tokens=4096,
        suggested_max_tokens=4096,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "o1": ModelDetail(
        id="o1",
        name="o1",
        description="OpenAI o1 推理模型，擅长复杂数学、科学推理",
        vendor_id="dashscope",
        input_context_window=200000,
        max_output_tokens=100000,
        suggested_max_tokens=100000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        knowledge_cutoff="2023-10",
        recommended=False,
        model_family="qwen",
    ),
    "o3-mini": ModelDetail(
        id="o3-mini",
        name="o3 Mini",
        description="OpenAI o3 轻量推理模型，支持可调推理努力",
        vendor_id="dashscope",
        input_context_window=200000,
        max_output_tokens=100000,
        suggested_max_tokens=100000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        knowledge_cutoff="2024-06",
        recommended=False,
        model_family="qwen",
    ),
    "qwen-flash": ModelDetail(
        id="qwen-flash",
        name="Qwen Flash",
        description="Qwen 高速文本模型，1M 超长上下文，适合低延迟任务。",
        vendor_id="dashscope",
        input_context_window=1000000,
        max_output_tokens=32000,
        suggested_max_tokens=32000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "qwen-max": ModelDetail(
        id="qwen-max",
        name="Qwen Max",
        description="Qwen 最强文本模型，适合复杂推理、深度分析和长文档理解。",
        vendor_id="dashscope",
        input_context_window=32768,
        max_output_tokens=8192,
        suggested_max_tokens=8192,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "qwen-omni-turbo": ModelDetail(
        id="qwen-omni-turbo",
        name="Qwen Omni Turbo",
        description="全模态模型（文本+图像+视频+音频），适合多模态交互场景。",
        vendor_id="dashscope",
        input_context_window=32768,
        max_output_tokens=4096,
        suggested_max_tokens=4096,
        capabilities=ModelCapabilities(text=True, image=True, video=True, audio=True),
        recommended=False,
        model_family="qwen",
    ),
    "qwen-plus": ModelDetail(
        id="qwen-plus",
        name="Qwen Plus",
        description="Qwen 主力文本模型，平衡性能与成本，适合日常研究对话。",
        vendor_id="dashscope",
        input_context_window=1000000,
        max_output_tokens=32000,
        suggested_max_tokens=32000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        recommended=True,
        model_family="qwen",
    ),
    "qwen-plus-0419": ModelDetail(
        id="qwen-plus-0419",
        name="Qwen Plus 0419",
        description="最新文本主力模型，长上下文",
        vendor_id="dashscope",
        input_context_window=1000000,
        max_output_tokens=16384,
        suggested_max_tokens=16384,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        recommended=True,
        model_family="qwen",
    ),
    "qwen-turbo": ModelDetail(
        id="qwen-turbo",
        name="Qwen Turbo",
        description="轻量快速模型，适合简单问答、摘要、分类等低延迟场景。",
        vendor_id="dashscope",
        input_context_window=1000000,
        max_output_tokens=4096,
        suggested_max_tokens=4096,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "qwen-turbo-0419": ModelDetail(
        id="qwen-turbo-0419",
        name="Qwen Turbo 0419",
        description="最新轻量文本模型，响应极快",
        vendor_id="dashscope",
        input_context_window=1000000,
        max_output_tokens=4096,
        suggested_max_tokens=4096,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "qwen-vl-max": ModelDetail(
        id="qwen-vl-max",
        name="Qwen VL Max",
        description="最强视觉语言模型，支持图像理解、图表提取、OCR。",
        vendor_id="dashscope",
        input_context_window=32768,
        max_output_tokens=4096,
        suggested_max_tokens=4096,
        capabilities=ModelCapabilities(text=True, image=True, video=False, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "qwen-vl-max-0319": ModelDetail(
        id="qwen-vl-max-0319",
        name="Qwen VL Max 0319",
        description="最新视觉语言模型，支持图像、视频理解",
        vendor_id="dashscope",
        input_context_window=131072,
        max_output_tokens=8192,
        suggested_max_tokens=8192,
        capabilities=ModelCapabilities(text=True, image=True, video=True, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "qwen-vl-ocr": ModelDetail(
        id="qwen-vl-ocr",
        name="Qwen VL OCR",
        description="专注于 OCR 识别和文档数字化的视觉模型。",
        vendor_id="dashscope",
        input_context_window=32768,
        max_output_tokens=4096,
        suggested_max_tokens=4096,
        capabilities=ModelCapabilities(text=True, image=True, video=False, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "qwen-vl-plus": ModelDetail(
        id="qwen-vl-plus",
        name="Qwen VL Plus",
        description="视觉语言模型，支持图文理解，性价比高。",
        vendor_id="dashscope",
        input_context_window=32768,
        max_output_tokens=4096,
        suggested_max_tokens=4096,
        capabilities=ModelCapabilities(text=True, image=True, video=False, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "qwen2-audio": ModelDetail(
        id="qwen2-audio",
        name="Qwen2 Audio",
        description="语音理解模型，支持语音识别、语音对话与音频分析。",
        vendor_id="dashscope",
        input_context_window=32768,
        max_output_tokens=4096,
        suggested_max_tokens=4096,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=True),
        recommended=False,
        model_family="qwen",
    ),
    "qwen2.5-14b-instruct": ModelDetail(
        id="qwen2.5-14b-instruct",
        name="Qwen2.5 14B Instruct",
        description="Qwen2.5 系列 14B 文本模型，轻量部署首选。",
        vendor_id="dashscope",
        input_context_window=32768,
        max_output_tokens=8000,
        suggested_max_tokens=8000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "qwen2.5-14b-instruct-1m": ModelDetail(
        id="qwen2.5-14b-instruct-1m",
        name="Qwen2.5 14B Instruct 1M",
        description="Qwen2.5 14B 长上下文文本模型，1M 上下文。",
        vendor_id="dashscope",
        input_context_window=1000000,
        max_output_tokens=8000,
        suggested_max_tokens=8000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "qwen2.5-32b-instruct": ModelDetail(
        id="qwen2.5-32b-instruct",
        name="Qwen2.5 32B Instruct",
        description="Qwen2.5 系列 32B 文本模型，三十二亿参数均衡之选。",
        vendor_id="dashscope",
        input_context_window=32768,
        max_output_tokens=8000,
        suggested_max_tokens=8000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "qwen2.5-72b-instruct": ModelDetail(
        id="qwen2.5-72b-instruct",
        name="Qwen2.5 72B Instruct",
        description="Qwen2.5 系列 72B 文本模型，适合大规模文本生成。",
        vendor_id="dashscope",
        input_context_window=32768,
        max_output_tokens=8000,
        suggested_max_tokens=8000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "qwen2.5-7b-instruct": ModelDetail(
        id="qwen2.5-7b-instruct",
        name="Qwen2.5 7B Instruct",
        description="Qwen2.5 7B 文本模型，32K 上下文。",
        vendor_id="dashscope",
        input_context_window=32768,
        max_output_tokens=8000,
        suggested_max_tokens=8000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "qwen2.5-7b-instruct-1m": ModelDetail(
        id="qwen2.5-7b-instruct-1m",
        name="Qwen2.5 7B Instruct 1M",
        description="Qwen2.5 7B 长上下文文本模型，1M 上下文。",
        vendor_id="dashscope",
        input_context_window=1000000,
        max_output_tokens=8000,
        suggested_max_tokens=8000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "qwen2.5-vl-32b-instruct": ModelDetail(
        id="qwen2.5-vl-32b-instruct",
        name="Qwen2.5 VL 32B",
        description="Qwen2.5 系列 32B 视觉语言模型，支持图像与视频理解。",
        vendor_id="dashscope",
        input_context_window=128000,
        max_output_tokens=8000,
        suggested_max_tokens=8000,
        capabilities=ModelCapabilities(text=True, image=True, video=True, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "qwen2.5-vl-3b-instruct": ModelDetail(
        id="qwen2.5-vl-3b-instruct",
        name="Qwen2.5 VL 3B",
        description="Qwen2.5 系列 3B 视觉语言模型，极致轻量，支持图像与视频理解。",
        vendor_id="dashscope",
        input_context_window=128000,
        max_output_tokens=8000,
        suggested_max_tokens=8000,
        capabilities=ModelCapabilities(text=True, image=True, video=True, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "qwen2.5-vl-72b-instruct": ModelDetail(
        id="qwen2.5-vl-72b-instruct",
        name="Qwen2.5 VL 72B",
        description="Qwen2.5 系列 72B 视觉语言模型，支持图像与视频理解。",
        vendor_id="dashscope",
        input_context_window=128000,
        max_output_tokens=8000,
        suggested_max_tokens=8000,
        capabilities=ModelCapabilities(text=True, image=True, video=True, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "qwen2.5-vl-7b-instruct": ModelDetail(
        id="qwen2.5-vl-7b-instruct",
        name="Qwen2.5 VL 7B",
        description="Qwen2.5 系列 7B 视觉语言模型，轻量部署，支持图像与视频理解。",
        vendor_id="dashscope",
        input_context_window=128000,
        max_output_tokens=8000,
        suggested_max_tokens=8000,
        capabilities=ModelCapabilities(text=True, image=True, video=True, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "qwen3-0.6b": ModelDetail(
        id="qwen3-0.6b",
        name="Qwen3 0.6B",
        description="Qwen3 0.6B 文本模型，32K 上下文。",
        vendor_id="dashscope",
        input_context_window=32768,
        max_output_tokens=8000,
        suggested_max_tokens=8000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "qwen3-1.7b": ModelDetail(
        id="qwen3-1.7b",
        name="Qwen3 1.7B",
        description="Qwen3 1.7B 文本模型，32K 上下文。",
        vendor_id="dashscope",
        input_context_window=32768,
        max_output_tokens=8000,
        suggested_max_tokens=8000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "qwen3-14b": ModelDetail(
        id="qwen3-14b",
        name="Qwen3 14B",
        description="Qwen3 14B 文本模型，128K 上下文。",
        vendor_id="dashscope",
        input_context_window=131072,
        max_output_tokens=8000,
        suggested_max_tokens=8000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "qwen3-235b-a22b": ModelDetail(
        id="qwen3-235b-a22b",
        name="Qwen3 235B",
        description="Qwen3 系列 MoE 旗舰模型，235B 总参数/22B 激活",
        vendor_id="dashscope",
        input_context_window=131072,
        max_output_tokens=16000,
        suggested_max_tokens=16000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "qwen3-235b-a22b-instruct-2507": ModelDetail(
        id="qwen3-235b-a22b-instruct-2507",
        name="Qwen3 235B Instruct 2507",
        description="Qwen3 235B 指令快照版本，128K 上下文。",
        vendor_id="dashscope",
        input_context_window=131072,
        max_output_tokens=32000,
        suggested_max_tokens=32000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "qwen3-235b-a22b-thinking-2507": ModelDetail(
        id="qwen3-235b-a22b-thinking-2507",
        name="Qwen3 235B Thinking 2507",
        description="Qwen3 235B 推理快照版本，128K 上下文。",
        vendor_id="dashscope",
        input_context_window=131072,
        max_output_tokens=32000,
        suggested_max_tokens=32000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "qwen3-30b-a3b": ModelDetail(
        id="qwen3-30b-a3b",
        name="Qwen3 30B A3B",
        description="Qwen3 30B A3B 文本模型，128K 上下文。",
        vendor_id="dashscope",
        input_context_window=131072,
        max_output_tokens=16000,
        suggested_max_tokens=16000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "qwen3-30b-a3b-instruct-2507": ModelDetail(
        id="qwen3-30b-a3b-instruct-2507",
        name="Qwen3 30B A3B Instruct 2507",
        description="Qwen3 30B A3B 指令快照版本，128K 上下文。",
        vendor_id="dashscope",
        input_context_window=131072,
        max_output_tokens=32000,
        suggested_max_tokens=32000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "qwen3-30b-a3b-thinking-2507": ModelDetail(
        id="qwen3-30b-a3b-thinking-2507",
        name="Qwen3 30B A3B Thinking 2507",
        description="Qwen3 30B A3B 推理快照版本，128K 上下文。",
        vendor_id="dashscope",
        input_context_window=131072,
        max_output_tokens=32000,
        suggested_max_tokens=32000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "qwen3-32b": ModelDetail(
        id="qwen3-32b",
        name="Qwen3 32B",
        description="Qwen3 32B 文本模型，128K 上下文。",
        vendor_id="dashscope",
        input_context_window=131072,
        max_output_tokens=16000,
        suggested_max_tokens=16000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "qwen3-4b": ModelDetail(
        id="qwen3-4b",
        name="Qwen3 4B",
        description="Qwen3 4B 文本模型，128K 上下文。",
        vendor_id="dashscope",
        input_context_window=131072,
        max_output_tokens=8000,
        suggested_max_tokens=8000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "qwen3-8b": ModelDetail(
        id="qwen3-8b",
        name="Qwen3 8B",
        description="Qwen3 8B 文本模型，128K 上下文。",
        vendor_id="dashscope",
        input_context_window=131072,
        max_output_tokens=8000,
        suggested_max_tokens=8000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "qwen3-coder-30b-a3b-instruct": ModelDetail(
        id="qwen3-coder-30b-a3b-instruct",
        name="Qwen3 Coder 30B A3B Instruct",
        description="Qwen3 Coder 开源指令模型，262K 上下文。",
        vendor_id="dashscope",
        input_context_window=262144,
        max_output_tokens=64000,
        suggested_max_tokens=64000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "qwen3-coder-480b-a35b-instruct": ModelDetail(
        id="qwen3-coder-480b-a35b-instruct",
        name="Qwen3 Coder 480B A35B Instruct",
        description="Qwen3 Coder 开源指令模型，262K 上下文。",
        vendor_id="dashscope",
        input_context_window=262144,
        max_output_tokens=64000,
        suggested_max_tokens=64000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "qwen3-coder-flash": ModelDetail(
        id="qwen3-coder-flash",
        name="Qwen3 Coder Flash",
        description="Qwen3 高速代码模型，1M 超长上下文，适合交互式代码生成。",
        vendor_id="dashscope",
        input_context_window=1000000,
        max_output_tokens=64000,
        suggested_max_tokens=64000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "qwen3-coder-flash-2025-07-28": ModelDetail(
        id="qwen3-coder-flash-2025-07-28",
        name="Qwen3 Coder Flash 2025-07-28",
        description="Qwen3 Coder Flash 快照版本，1M 超长上下文。",
        vendor_id="dashscope",
        input_context_window=1000000,
        max_output_tokens=64000,
        suggested_max_tokens=64000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "qwen3-coder-next": ModelDetail(
        id="qwen3-coder-next",
        name="Qwen3 Coder Next",
        description="Qwen3 下一代代码模型，262K 上下文，适合新一代编程工作流。",
        vendor_id="dashscope",
        input_context_window=262144,
        max_output_tokens=64000,
        suggested_max_tokens=64000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "qwen3-coder-plus": ModelDetail(
        id="qwen3-coder-plus",
        name="Qwen3 Coder Plus",
        description="Qwen3 代码模型，1M 超长上下文，适合复杂编程任务与代码理解。",
        vendor_id="dashscope",
        input_context_window=1000000,
        max_output_tokens=64000,
        suggested_max_tokens=64000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "qwen3-coder-plus-2025-07-22": ModelDetail(
        id="qwen3-coder-plus-2025-07-22",
        name="Qwen3 Coder Plus 2025-07-22",
        description="Qwen3 Coder Plus 快照版本，1M 超长上下文。",
        vendor_id="dashscope",
        input_context_window=1000000,
        max_output_tokens=64000,
        suggested_max_tokens=64000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "qwen3-coder-plus-2025-09-23": ModelDetail(
        id="qwen3-coder-plus-2025-09-23",
        name="Qwen3 Coder Plus 2025-09-23",
        description="Qwen3 Coder Plus 快照版本，1M 超长上下文。",
        vendor_id="dashscope",
        input_context_window=1000000,
        max_output_tokens=64000,
        suggested_max_tokens=64000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "qwen3-max": ModelDetail(
        id="qwen3-max",
        name="Qwen3 Max",
        description="Qwen3 旗舰文本模型，256K 上下文，适合复杂推理与工具调用。",
        vendor_id="dashscope",
        input_context_window=262144,
        max_output_tokens=64000,
        suggested_max_tokens=64000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "qwen3-max-2025-09-23": ModelDetail(
        id="qwen3-max-2025-09-23",
        name="Qwen3 Max 2025-09-23",
        description="Qwen3 Max 快照版本，256K 上下文。",
        vendor_id="dashscope",
        input_context_window=262144,
        max_output_tokens=64000,
        suggested_max_tokens=64000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "qwen3-max-2026-01-23": ModelDetail(
        id="qwen3-max-2026-01-23",
        name="Qwen3 Max 2026-01-23",
        description="Qwen3 Max 快照版本，256K 上下文。",
        vendor_id="dashscope",
        input_context_window=262144,
        max_output_tokens=64000,
        suggested_max_tokens=64000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "qwen3-max-preview": ModelDetail(
        id="qwen3-max-preview",
        name="Qwen3 Max Preview",
        description="Qwen3 Max 预览版本，256K 上下文。",
        vendor_id="dashscope",
        input_context_window=262144,
        max_output_tokens=64000,
        suggested_max_tokens=64000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "qwen3-next-80b-a3b-instruct": ModelDetail(
        id="qwen3-next-80b-a3b-instruct",
        name="Qwen3 Next 80B Instruct",
        description="Qwen3 Next 80B 指令模型，128K 上下文。",
        vendor_id="dashscope",
        input_context_window=131072,
        max_output_tokens=32000,
        suggested_max_tokens=32000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "qwen3-next-80b-a3b-thinking": ModelDetail(
        id="qwen3-next-80b-a3b-thinking",
        name="Qwen3 Next 80B Thinking",
        description="Qwen3 Next 80B 推理模型，128K 上下文。",
        vendor_id="dashscope",
        input_context_window=131072,
        max_output_tokens=32000,
        suggested_max_tokens=32000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "qwen3-vl-235b-a22b-instruct": ModelDetail(
        id="qwen3-vl-235b-a22b-instruct",
        name="Qwen3 VL 235B A22B Instruct",
        description="Qwen3 VL 系列 MoE 视觉语言指令模型，235B 总参数，支持函数调用与图像视频理解。",
        vendor_id="dashscope",
        input_context_window=131072,
        max_output_tokens=8000,
        suggested_max_tokens=8000,
        capabilities=ModelCapabilities(text=True, image=True, video=True, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "qwen3-vl-30b-a3b-instruct": ModelDetail(
        id="qwen3-vl-30b-a3b-instruct",
        name="Qwen3 VL 30B A3B Instruct",
        description="Qwen3 VL MoE 视觉语言指令模型，30B 激活参数，支持函数调用与图像视频理解。",
        vendor_id="dashscope",
        input_context_window=131072,
        max_output_tokens=8000,
        suggested_max_tokens=8000,
        capabilities=ModelCapabilities(text=True, image=True, video=True, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "qwen3-vl-32b-instruct": ModelDetail(
        id="qwen3-vl-32b-instruct",
        name="Qwen3 VL 32B Instruct",
        description="Qwen3 VL 系列 32B 视觉语言指令模型，支持函数调用与图像视频理解。",
        vendor_id="dashscope",
        input_context_window=131072,
        max_output_tokens=8000,
        suggested_max_tokens=8000,
        capabilities=ModelCapabilities(text=True, image=True, video=True, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "qwen3-vl-8b-instruct": ModelDetail(
        id="qwen3-vl-8b-instruct",
        name="Qwen3 VL 8B Instruct",
        description="Qwen3 VL 系列 8B 视觉语言指令模型，轻量部署，支持函数调用与图像视频理解。",
        vendor_id="dashscope",
        input_context_window=131072,
        max_output_tokens=8000,
        suggested_max_tokens=8000,
        capabilities=ModelCapabilities(text=True, image=True, video=True, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "qwen3-vl-flash": ModelDetail(
        id="qwen3-vl-flash",
        name="Qwen3 VL Flash",
        description="Qwen3 系列高速视觉语言模型，支持函数调用与图像视频理解。",
        vendor_id="dashscope",
        input_context_window=262144,
        max_output_tokens=32000,
        suggested_max_tokens=32000,
        capabilities=ModelCapabilities(text=True, image=True, video=True, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "qwen3-vl-plus": ModelDetail(
        id="qwen3-vl-plus",
        name="Qwen3 VL Plus",
        description="Qwen3 系列视觉语言旗舰模型，支持函数调用与图像视频理解。",
        vendor_id="dashscope",
        input_context_window=262144,
        max_output_tokens=32000,
        suggested_max_tokens=32000,
        capabilities=ModelCapabilities(text=True, image=True, video=True, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "qwen3.5-122b-a10b": ModelDetail(
        id="qwen3.5-122b-a10b",
        name="Qwen3.5 122B A10B",
        description="Qwen3.5 系列 MoE 视觉语言模型，122B 总参数/10B 激活，支持图像与视频理解。",
        vendor_id="dashscope",
        input_context_window=262144,
        max_output_tokens=64000,
        suggested_max_tokens=64000,
        capabilities=ModelCapabilities(text=True, image=True, video=True, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "qwen3.5-27b": ModelDetail(
        id="qwen3.5-27b",
        name="Qwen3.5 27B",
        description="Qwen3.5 系列 27B 密集视觉语言模型，支持图像与视频理解。",
        vendor_id="dashscope",
        input_context_window=262144,
        max_output_tokens=64000,
        suggested_max_tokens=64000,
        capabilities=ModelCapabilities(text=True, image=True, video=True, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "qwen3.5-35b-a3b": ModelDetail(
        id="qwen3.5-35b-a3b",
        name="Qwen3.5 35B A3B",
        description="Qwen3.5 系列 MoE 轻量视觉语言模型，高效推理，支持图像与视频理解。",
        vendor_id="dashscope",
        input_context_window=262144,
        max_output_tokens=64000,
        suggested_max_tokens=64000,
        capabilities=ModelCapabilities(text=True, image=True, video=True, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "qwen3.5-397b-a17b": ModelDetail(
        id="qwen3.5-397b-a17b",
        name="Qwen3.5 397B A17B",
        description="Qwen3.5 系列 MoE 视觉语言旗舰模型，397B 总参数/17B 激活，支持图像与视频理解。",
        vendor_id="dashscope",
        input_context_window=262144,
        max_output_tokens=64000,
        suggested_max_tokens=64000,
        capabilities=ModelCapabilities(text=True, image=True, video=True, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "qwen3.5-flash": ModelDetail(
        id="qwen3.5-flash",
        name="Qwen3.5 Flash",
        description="Qwen3.5 系列高速视觉语言模型，1M 超长上下文，支持图像与视频理解。",
        vendor_id="dashscope",
        input_context_window=1000000,
        max_output_tokens=64000,
        suggested_max_tokens=64000,
        capabilities=ModelCapabilities(text=True, image=True, video=True, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "qwen3.5-flash-2026-02-23": ModelDetail(
        id="qwen3.5-flash-2026-02-23",
        name="Qwen3.5 Flash 2026-02-23",
        description="Qwen3.5 Flash 快照版本，1M 超长上下文，支持图像与视频理解。",
        vendor_id="dashscope",
        input_context_window=1000000,
        max_output_tokens=64000,
        suggested_max_tokens=64000,
        capabilities=ModelCapabilities(text=True, image=True, video=True, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "qwen3.5-omni-flash": ModelDetail(
        id="qwen3.5-omni-flash",
        name="Qwen3.5 Omni Flash",
        description="全模态轻量 HTTP 模型（文本+图像+视频+音频），支持函数调用，256K 上下文。",
        vendor_id="dashscope",
        input_context_window=256000,
        max_output_tokens=64000,
        suggested_max_tokens=64000,
        capabilities=ModelCapabilities(text=True, image=True, video=True, audio=True),
        recommended=False,
        model_family="qwen",
    ),
    "qwen3.5-omni-flash-2026-03-15": ModelDetail(
        id="qwen3.5-omni-flash-2026-03-15",
        name="Qwen3.5 Omni Flash (2026-03-15)",
        description="Qwen3.5 Omni Flash 快照，全模态 HTTP 模型。",
        vendor_id="dashscope",
        input_context_window=256000,
        max_output_tokens=64000,
        suggested_max_tokens=64000,
        capabilities=ModelCapabilities(text=True, image=True, video=True, audio=True),
        recommended=False,
        model_family="qwen",
    ),
    "qwen3.5-omni-plus": ModelDetail(
        id="qwen3.5-omni-plus",
        name="Qwen3.5 Omni Plus",
        description="全模态 HTTP 模型（文本+图像+视频+音频），支持函数调用，256K 上下文。",
        vendor_id="dashscope",
        input_context_window=256000,
        max_output_tokens=64000,
        suggested_max_tokens=64000,
        capabilities=ModelCapabilities(text=True, image=True, video=True, audio=True),
        recommended=False,
        model_family="qwen",
    ),
    "qwen3.5-omni-plus-2026-03-15": ModelDetail(
        id="qwen3.5-omni-plus-2026-03-15",
        name="Qwen3.5 Omni Plus (2026-03-15)",
        description="Qwen3.5 Omni Plus 快照，全模态 HTTP 模型。",
        vendor_id="dashscope",
        input_context_window=256000,
        max_output_tokens=64000,
        suggested_max_tokens=64000,
        capabilities=ModelCapabilities(text=True, image=True, video=True, audio=True),
        recommended=False,
        model_family="qwen",
    ),
    "qwen3.5-plus": ModelDetail(
        id="qwen3.5-plus",
        name="Qwen3.5 Plus",
        description="Qwen3.5 系列视觉语言旗舰模型，1M 超长上下文，支持图像与视频理解。",
        vendor_id="dashscope",
        input_context_window=1000000,
        max_output_tokens=64000,
        suggested_max_tokens=64000,
        capabilities=ModelCapabilities(text=True, image=True, video=True, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "qwen3.5-plus-2026-02-15": ModelDetail(
        id="qwen3.5-plus-2026-02-15",
        name="Qwen3.5 Plus 2026-02-15",
        description="Qwen3.5 Plus 快照版本，1M 超长上下文，支持图像与视频理解。",
        vendor_id="dashscope",
        input_context_window=1000000,
        max_output_tokens=64000,
        suggested_max_tokens=64000,
        capabilities=ModelCapabilities(text=True, image=True, video=True, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "qwen3.5-plus-2026-04-20": ModelDetail(
        id="qwen3.5-plus-2026-04-20",
        name="Qwen3.5 Plus 2026-04-20",
        description="Qwen3.5 Plus 快照版本，1M 超长上下文，支持图像与视频理解。",
        vendor_id="dashscope",
        input_context_window=1000000,
        max_output_tokens=64000,
        suggested_max_tokens=64000,
        capabilities=ModelCapabilities(text=True, image=True, video=True, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "qwen3.6-27b": ModelDetail(
        id="qwen3.6-27b",
        name="Qwen3.6 27B",
        description="Qwen3.6 27B 文本模型，256K 上下文。",
        vendor_id="dashscope",
        input_context_window=262144,
        max_output_tokens=64000,
        suggested_max_tokens=64000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "qwen3.6-35b-a3b": ModelDetail(
        id="qwen3.6-35b-a3b",
        name="Qwen3.6 35B A3B",
        description="Qwen3.6 系列 MoE 视觉语言模型，高效推理，支持图像与视频理解。",
        vendor_id="dashscope",
        input_context_window=262144,
        max_output_tokens=64000,
        suggested_max_tokens=64000,
        capabilities=ModelCapabilities(text=True, image=True, video=True, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "qwen3.6-flash": ModelDetail(
        id="qwen3.6-flash",
        name="Qwen3.6 Flash",
        description="Qwen3.6 系列高速视觉语言模型，1M 超长上下文，支持图像与视频理解。",
        vendor_id="dashscope",
        input_context_window=1000000,
        max_output_tokens=64000,
        suggested_max_tokens=64000,
        capabilities=ModelCapabilities(text=True, image=True, video=True, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "qwen3.6-flash-2026-04-16": ModelDetail(
        id="qwen3.6-flash-2026-04-16",
        name="Qwen3.6 Flash 2026-04-16",
        description="Qwen3.6 Flash 快照版本，1M 超长上下文，支持图像与视频理解。",
        vendor_id="dashscope",
        input_context_window=1000000,
        max_output_tokens=64000,
        suggested_max_tokens=64000,
        capabilities=ModelCapabilities(text=True, image=True, video=True, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "qwen3.6-max-preview": ModelDetail(
        id="qwen3.6-max-preview",
        name="Qwen3.6 Max Preview",
        description="Qwen3.6 预览版旗舰文本模型，256K 上下文。",
        vendor_id="dashscope",
        input_context_window=262144,
        max_output_tokens=64000,
        suggested_max_tokens=64000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "qwen3.6-plus": ModelDetail(
        id="qwen3.6-plus",
        name="Qwen3.6 Plus",
        description="Qwen3.6 系列视觉语言模型，1M 超长上下文，支持图像与视频理解。",
        vendor_id="dashscope",
        input_context_window=1000000,
        max_output_tokens=64000,
        suggested_max_tokens=64000,
        capabilities=ModelCapabilities(text=True, image=True, video=True, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "qwen3.6-plus-2026-04-02": ModelDetail(
        id="qwen3.6-plus-2026-04-02",
        name="Qwen3.6 Plus 2026-04-02",
        description="Qwen3.6 Plus 快照版本，1M 超长上下文，支持图像与视频理解。",
        vendor_id="dashscope",
        input_context_window=1000000,
        max_output_tokens=64000,
        suggested_max_tokens=64000,
        capabilities=ModelCapabilities(text=True, image=True, video=True, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "qwen3.7-max": ModelDetail(
        id="qwen3.7-max",
        name="Qwen3.7 Max",
        description="Qwen3.7 最强文本模型，1M 超长上下文，适合复杂推理与深度分析。",
        vendor_id="dashscope",
        input_context_window=1000000,
        max_output_tokens=64000,
        suggested_max_tokens=64000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "qwen3.7-max-2026-05-17": ModelDetail(
        id="qwen3.7-max-2026-05-17",
        name="Qwen3.7 Max 2026-05-17",
        description="Qwen3.7 Max 快照版本，1M 超长上下文。",
        vendor_id="dashscope",
        input_context_window=1000000,
        max_output_tokens=64000,
        suggested_max_tokens=64000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "qwen3.7-max-2026-05-20": ModelDetail(
        id="qwen3.7-max-2026-05-20",
        name="Qwen3.7 Max 2026-05-20",
        description="Qwen3.7 Max 快照版本，1M 超长上下文。",
        vendor_id="dashscope",
        input_context_window=1000000,
        max_output_tokens=64000,
        suggested_max_tokens=64000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "qwen3.7-max-2026-06-08": ModelDetail(
        id="qwen3.7-max-2026-06-08",
        name="Qwen3.7 Max 2026-06-08",
        description="Qwen3.7 Max 快照版本，1M 超长上下文。",
        vendor_id="dashscope",
        input_context_window=1000000,
        max_output_tokens=64000,
        suggested_max_tokens=64000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "qwen3.7-max-preview": ModelDetail(
        id="qwen3.7-max-preview",
        name="Qwen3.7 Max Preview",
        description="Qwen3.7 Max 预览版，1M 超长上下文。",
        vendor_id="dashscope",
        input_context_window=1000000,
        max_output_tokens=64000,
        suggested_max_tokens=64000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "qwen3.7-plus": ModelDetail(
        id="qwen3.7-plus",
        name="Qwen3.7 Plus",
        description="Qwen3.7 系列视觉语言模型，1M 超长上下文，支持图像与视频理解。",
        vendor_id="dashscope",
        input_context_window=1000000,
        max_output_tokens=64000,
        suggested_max_tokens=64000,
        capabilities=ModelCapabilities(text=True, image=True, video=True, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "qwen3.7-plus-2026-05-26": ModelDetail(
        id="qwen3.7-plus-2026-05-26",
        name="Qwen3.7 Plus 2026-05-26",
        description="Qwen3.7 Plus 快照版本，1M 超长上下文，支持图像与视频理解。",
        vendor_id="dashscope",
        input_context_window=1000000,
        max_output_tokens=64000,
        suggested_max_tokens=64000,
        capabilities=ModelCapabilities(text=True, image=True, video=True, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "qwq-32b": ModelDetail(
        id="qwq-32b",
        name="QWQ 32B",
        description="推理增强模型（类 o1），擅长数学、逻辑和多步推理。",
        vendor_id="dashscope",
        input_context_window=32768,
        max_output_tokens=8192,
        suggested_max_tokens=8192,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    "qwq-plus": ModelDetail(
        id="qwq-plus",
        name="QWQ Plus",
        description="新一代推理模型，更强的思维链与复杂推理能力。",
        vendor_id="dashscope",
        input_context_window=131072,
        max_output_tokens=16384,
        suggested_max_tokens=16384,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        recommended=False,
        model_family="qwen",
    ),
    # -- fun-asr --
    "fun-asr": ModelDetail(
        id="fun-asr", name="fun-asr",
        description="阿里云语音识别模型。",
        vendor_id="dashscope", input_context_window=32768,
        max_output_tokens=1, suggested_max_tokens=1,
        capabilities=ModelCapabilities(text=True, audio=True),
        knowledge_cutoff="2026-06", model_family="fun-asr",
    ),
    # -- fun-asr-realtime --
    "fun-asr-realtime": ModelDetail(
        id="fun-asr-realtime", name="fun-asr-realtime",
        description="阿里云实时语音识别模型。",
        vendor_id="dashscope", input_context_window=32768,
        max_output_tokens=1, suggested_max_tokens=1,
        capabilities=ModelCapabilities(text=True, audio=True),
        knowledge_cutoff="2026-06", model_family="fun-asr",
    ),
    # -- fun-music-v1 --
    "fun-music-v1": ModelDetail(
        id="fun-music-v1", name="fun-music-v1",
        description="阿里云 AI 音乐生成模型。",
        vendor_id="dashscope", input_context_window=1,
        max_output_tokens=1, suggested_max_tokens=1,
        capabilities=ModelCapabilities(audio=True),
        knowledge_cutoff="2026-06", model_family="fun-music",
    ),
    # -- text-embedding-v4 --
    "text-embedding-v4": ModelDetail(
        id="text-embedding-v4", name="text-embedding-v4",
        description="阿里云文本向量化模型。",
        vendor_id="dashscope", input_context_window=8192,
        max_output_tokens=1, suggested_max_tokens=1,
        capabilities=ModelCapabilities(text=True),
        knowledge_cutoff="2026-06", model_family="embedding",
    ),
    # -- tongyi-embedding-vision-plus --
    "tongyi-embedding-vision-plus": ModelDetail(
        id="tongyi-embedding-vision-plus", name="tongyi-embedding-vision-plus",
        description="阿里云多模态向量化模型。",
        vendor_id="dashscope", input_context_window=16384,
        max_output_tokens=1, suggested_max_tokens=1,
        capabilities=ModelCapabilities(text=True, image=True),
        knowledge_cutoff="2026-06", model_family="embedding",
    ),
    # -- wan2.7-image-pro --
    "wan2.7-image-pro": ModelDetail(
        id="wan2.7-image-pro", name="wan2.7-image-pro",
        description="阿里云万相文生图模型。",
        vendor_id="dashscope", input_context_window=1,
        max_output_tokens=1, suggested_max_tokens=1,
        capabilities=ModelCapabilities(text=True, image=True),
        knowledge_cutoff="2026-06", model_family="wan",
    ),

}

def register(target: dict[str, ModelDetail]) -> None:
    """Merge Qwen models into the target repository dictionary."""
    target.update(MODELS)
