"""Qwen/DashScope model data provider."""

from __future__ import annotations

from app.model_info.schemas import ModelCapabilities, ModelDetail

MODELS: dict[str, ModelDetail] = {
    "qwen3.8-max": ModelDetail(
        id="qwen3.8-max",
        name="Qwen3.8 Max",
        description="阿里云百炼 Qwen3.8 旗舰模型，1M 上下文，支持文本、图片与视频理解。",
        vendor_id="dashscope",
        input_context_window=1_000_000,
        max_output_tokens=131_072,
        suggested_max_tokens=64_000,
        capabilities=ModelCapabilities(text=True, image=True, video=True, audio=False),
        pricing_input_per_1m=2,
        pricing_output_per_1m=6,
        recommended=True,
        model_family="qwen3.8",
    ),
    "qwen3.7-max": ModelDetail(
        id="qwen3.7-max",
        name="Qwen3.7 Max",
        description="Qwen3.7 系列旗舰文本模型，1M 上下文，面向复杂推理与长程任务。",
        vendor_id="dashscope",
        input_context_window=1_000_000,
        max_output_tokens=131_072,
        suggested_max_tokens=64_000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        pricing_input_per_1m=2.5,
        pricing_output_per_1m=7.5,
        model_family="qwen3.7",
    ),
    "qwen3.7-max-2026-06-08": ModelDetail(
        id="qwen3.7-max-2026-06-08",
        name="Qwen3.7 Max 2026-06-08",
        description="Qwen3.7 Max 快照版本（2026-06-08）。",
        vendor_id="dashscope",
        input_context_window=1_000_000,
        max_output_tokens=131_072,
        suggested_max_tokens=64_000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        pricing_input_per_1m=2.5,
        pricing_output_per_1m=7.5,
        model_family="qwen3.7",
    ),
    "qwen3.7-max-2026-05-20": ModelDetail(
        id="qwen3.7-max-2026-05-20",
        name="Qwen3.7 Max 2026-05-20",
        description="Qwen3.7 Max 快照版本（2026-05-20）。",
        vendor_id="dashscope",
        input_context_window=1_000_000,
        max_output_tokens=131_072,
        suggested_max_tokens=64_000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        pricing_input_per_1m=2.5,
        pricing_output_per_1m=7.5,
        model_family="qwen3.7",
    ),
    "qwen3.7-max-preview": ModelDetail(
        id="qwen3.7-max-preview",
        name="Qwen3.7 Max Preview",
        description="Qwen3.7 Max 预览版本，1M 上下文。",
        vendor_id="dashscope",
        input_context_window=1_000_000,
        max_output_tokens=131_072,
        suggested_max_tokens=64_000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        pricing_input_per_1m=2.5,
        pricing_output_per_1m=7.5,
        model_family="qwen3.7",
    ),
    "qwen3.7-max-2026-05-17": ModelDetail(
        id="qwen3.7-max-2026-05-17",
        name="Qwen3.7 Max 2026-05-17",
        description="Qwen3.7 Max 快照版本（2026-05-17）。",
        vendor_id="dashscope",
        input_context_window=1_000_000,
        max_output_tokens=131_072,
        suggested_max_tokens=64_000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        pricing_input_per_1m=2.5,
        pricing_output_per_1m=7.5,
        model_family="qwen3.7",
    ),
    "qwen3.7-plus": ModelDetail(
        id="qwen3.7-plus",
        name="Qwen3.7 Plus",
        description="Qwen3.7 Plus 多模态智能体模型，1M 上下文，支持文本、图片与视频输入。",
        vendor_id="dashscope",
        input_context_window=1_000_000,
        max_output_tokens=131_072,
        suggested_max_tokens=64_000,
        capabilities=ModelCapabilities(text=True, image=True, video=True, audio=False),
        pricing_input_per_1m=0.5,
        pricing_output_per_1m=3,
        recommended=True,
        model_family="qwen3.7",
    ),
    "qwen3.7-plus-2026-05-26": ModelDetail(
        id="qwen3.7-plus-2026-05-26",
        name="Qwen3.7 Plus 2026-05-26",
        description="Qwen3.7 Plus 快照版本（2026-05-26）。",
        vendor_id="dashscope",
        input_context_window=1_000_000,
        max_output_tokens=131_072,
        suggested_max_tokens=64_000,
        capabilities=ModelCapabilities(text=True, image=True, video=True, audio=False),
        pricing_input_per_1m=0.5,
        pricing_output_per_1m=3,
        model_family="qwen3.7",
    ),
    "qwen3.7-flash": ModelDetail(
        id="qwen3.7-flash",
        name="Qwen3.7 Flash",
        description="Qwen3.7 Flash 轻量多模态模型，1M 上下文，低时延高吞吐。",
        vendor_id="dashscope",
        input_context_window=1_000_000,
        max_output_tokens=131_072,
        suggested_max_tokens=64_000,
        capabilities=ModelCapabilities(text=True, image=True, video=True, audio=False),
        pricing_input_per_1m=0.03,
        pricing_output_per_1m=0.12,
        model_family="qwen3.7",
    ),
    "qwen3.6-max-preview": ModelDetail(
        id="qwen3.6-max-preview",
        name="Qwen3.6 Max Preview",
        description="Qwen3.6 系列预览旗舰模型，262K 上下文。",
        vendor_id="dashscope",
        input_context_window=262_144,
        max_output_tokens=65_536,
        suggested_max_tokens=64_000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        pricing_input_per_1m=1.3,
        pricing_output_per_1m=7.8,
        model_family="qwen3.6",
    ),
    "qwen3.6-plus": ModelDetail(
        id="qwen3.6-plus",
        name="Qwen3.6 Plus",
        description="Qwen3.6 Plus 原生视觉语言模型，1M 上下文，支持文本、图片与视频输入。",
        vendor_id="dashscope",
        input_context_window=1_000_000,
        max_output_tokens=65_536,
        suggested_max_tokens=64_000,
        capabilities=ModelCapabilities(text=True, image=True, video=True, audio=False),
        pricing_input_per_1m=0.5,
        pricing_output_per_1m=3,
        model_family="qwen3.6",
    ),
    "qwen3.6-plus-2026-04-02": ModelDetail(
        id="qwen3.6-plus-2026-04-02",
        name="Qwen3.6 Plus 2026-04-02",
        description="Qwen3.6 Plus 快照版本（2026-04-02）。",
        vendor_id="dashscope",
        input_context_window=1_000_000,
        max_output_tokens=65_536,
        suggested_max_tokens=64_000,
        capabilities=ModelCapabilities(text=True, image=True, video=True, audio=False),
        pricing_input_per_1m=0.5,
        pricing_output_per_1m=3,
        model_family="qwen3.6",
    ),
    "qwen3.6-flash": ModelDetail(
        id="qwen3.6-flash",
        name="Qwen3.6 Flash",
        description="Qwen3.6 Flash 轻量视觉语言模型，1M 上下文。",
        vendor_id="dashscope",
        input_context_window=1_000_000,
        max_output_tokens=65_536,
        suggested_max_tokens=64_000,
        capabilities=ModelCapabilities(text=True, image=True, video=True, audio=False),
        pricing_input_per_1m=0.19,
        pricing_output_per_1m=1.13,
        model_family="qwen3.6",
    ),
    "qwen3.6-flash-2026-04-16": ModelDetail(
        id="qwen3.6-flash-2026-04-16",
        name="Qwen3.6 Flash 2026-04-16",
        description="Qwen3.6 Flash 快照版本（2026-04-16）。",
        vendor_id="dashscope",
        input_context_window=1_000_000,
        max_output_tokens=65_536,
        suggested_max_tokens=64_000,
        capabilities=ModelCapabilities(text=True, image=True, video=True, audio=False),
        pricing_input_per_1m=0.19,
        pricing_output_per_1m=1.13,
        model_family="qwen3.6",
    ),
    "qwen3.6-27b": ModelDetail(
        id="qwen3.6-27b",
        name="Qwen3.6 27B",
        description="Qwen3.6 开源 27B 文本模型，262K 上下文。",
        vendor_id="dashscope",
        input_context_window=262_144,
        max_output_tokens=65_536,
        suggested_max_tokens=64_000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        pricing_input_per_1m=0.6,
        pricing_output_per_1m=3.6,
        model_family="qwen3.6",
    ),
    "qwen3.6-35b-a3b": ModelDetail(
        id="qwen3.6-35b-a3b",
        name="Qwen3.6 35B A3B",
        description="Qwen3.6 开源 35B-A3B 视觉语言模型，262K 上下文。",
        vendor_id="dashscope",
        input_context_window=262_144,
        max_output_tokens=65_536,
        suggested_max_tokens=64_000,
        capabilities=ModelCapabilities(text=True, image=True, video=True, audio=False),
        pricing_input_per_1m=0.25,
        pricing_output_per_1m=1.49,
        model_family="qwen3.6",
    ),
    "qwen3.5-plus": ModelDetail(
        id="qwen3.5-plus",
        name="Qwen3.5 Plus",
        description="Qwen3.5 Plus 视觉语言模型，1M 上下文，支持文本、图片与视频输入。",
        vendor_id="dashscope",
        input_context_window=1_000_000,
        max_output_tokens=65_536,
        suggested_max_tokens=64_000,
        capabilities=ModelCapabilities(text=True, image=True, video=True, audio=False),
        pricing_input_per_1m=0.4,
        pricing_output_per_1m=2.4,
        model_family="qwen3.5",
    ),
    "qwen3.5-plus-2026-04-20": ModelDetail(
        id="qwen3.5-plus-2026-04-20",
        name="Qwen3.5 Plus 2026-04-20",
        description="Qwen3.5 Plus 快照版本（2026-04-20）。",
        vendor_id="dashscope",
        input_context_window=1_000_000,
        max_output_tokens=65_536,
        suggested_max_tokens=64_000,
        capabilities=ModelCapabilities(text=True, image=True, video=True, audio=False),
        pricing_input_per_1m=0.4,
        pricing_output_per_1m=2.4,
        model_family="qwen3.5",
    ),
    "qwen3.5-plus-2026-02-15": ModelDetail(
        id="qwen3.5-plus-2026-02-15",
        name="Qwen3.5 Plus 2026-02-15",
        description="Qwen3.5 Plus 快照版本（2026-02-15）。",
        vendor_id="dashscope",
        input_context_window=1_000_000,
        max_output_tokens=65_536,
        suggested_max_tokens=64_000,
        capabilities=ModelCapabilities(text=True, image=True, video=True, audio=False),
        pricing_input_per_1m=0.4,
        pricing_output_per_1m=2.4,
        model_family="qwen3.5",
    ),
    "qwen3.5-flash": ModelDetail(
        id="qwen3.5-flash",
        name="Qwen3.5 Flash",
        description="Qwen3.5 Flash 轻量视觉语言模型，1M 上下文。",
        vendor_id="dashscope",
        input_context_window=1_000_000,
        max_output_tokens=65_536,
        suggested_max_tokens=64_000,
        capabilities=ModelCapabilities(text=True, image=True, video=True, audio=False),
        model_family="qwen3.5",
    ),
    "qwen3.5-flash-2026-02-23": ModelDetail(
        id="qwen3.5-flash-2026-02-23",
        name="Qwen3.5 Flash 2026-02-23",
        description="Qwen3.5 Flash 快照版本（2026-02-23）。",
        vendor_id="dashscope",
        input_context_window=1_000_000,
        max_output_tokens=65_536,
        suggested_max_tokens=64_000,
        capabilities=ModelCapabilities(text=True, image=True, video=True, audio=False),
        model_family="qwen3.5",
    ),
    "qwen3.5-397b-a17b": ModelDetail(
        id="qwen3.5-397b-a17b",
        name="Qwen3.5 397B A17B",
        description="Qwen3.5 开源 397B-A17B 视觉语言模型，262K 上下文。",
        vendor_id="dashscope",
        input_context_window=262_144,
        max_output_tokens=65_536,
        suggested_max_tokens=64_000,
        capabilities=ModelCapabilities(text=True, image=True, video=True, audio=False),
        pricing_input_per_1m=0.6,
        pricing_output_per_1m=3.6,
        model_family="qwen3.5",
    ),
    "qwen3.5-122b-a10b": ModelDetail(
        id="qwen3.5-122b-a10b",
        name="Qwen3.5 122B A10B",
        description="Qwen3.5 开源 122B-A10B 视觉语言模型，262K 上下文。",
        vendor_id="dashscope",
        input_context_window=262_144,
        max_output_tokens=65_536,
        suggested_max_tokens=64_000,
        capabilities=ModelCapabilities(text=True, image=True, video=True, audio=False),
        pricing_input_per_1m=0.4,
        pricing_output_per_1m=3.2,
        model_family="qwen3.5",
    ),
    "qwen3.5-27b": ModelDetail(
        id="qwen3.5-27b",
        name="Qwen3.5 27B",
        description="Qwen3.5 开源 27B 视觉语言模型，262K 上下文。",
        vendor_id="dashscope",
        input_context_window=262_144,
        max_output_tokens=65_536,
        suggested_max_tokens=64_000,
        capabilities=ModelCapabilities(text=True, image=True, video=True, audio=False),
        pricing_input_per_1m=0.3,
        pricing_output_per_1m=2.4,
        model_family="qwen3.5",
    ),
    "qwen3.5-35b-a3b": ModelDetail(
        id="qwen3.5-35b-a3b",
        name="Qwen3.5 35B A3B",
        description="Qwen3.5 开源 35B-A3B 视觉语言模型，262K 上下文。",
        vendor_id="dashscope",
        input_context_window=262_144,
        max_output_tokens=65_536,
        suggested_max_tokens=64_000,
        capabilities=ModelCapabilities(text=True, image=True, video=True, audio=False),
        pricing_input_per_1m=0.25,
        pricing_output_per_1m=2,
        model_family="qwen3.5",
    ),
    "qwen3.5-omni-plus": ModelDetail(
        id="qwen3.5-omni-plus",
        name="Qwen3.5 Omni Plus",
        description="Qwen3.5 全模态 HTTP 模型（文本+图片+视频+音频），262K 上下文。",
        vendor_id="dashscope",
        input_context_window=262_144,
        max_output_tokens=65_536,
        suggested_max_tokens=64_000,
        capabilities=ModelCapabilities(text=True, image=True, video=True, audio=True),
        model_family="qwen-omni",
    ),
    "qwen3.5-omni-plus-2026-03-15": ModelDetail(
        id="qwen3.5-omni-plus-2026-03-15",
        name="Qwen3.5 Omni Plus (2026-03-15)",
        description="Qwen3.5 Omni Plus 快照版本（2026-03-15）。",
        vendor_id="dashscope",
        input_context_window=262_144,
        max_output_tokens=65_536,
        suggested_max_tokens=64_000,
        capabilities=ModelCapabilities(text=True, image=True, video=True, audio=True),
        model_family="qwen-omni",
    ),
    "qwen3.5-omni-flash": ModelDetail(
        id="qwen3.5-omni-flash",
        name="Qwen3.5 Omni Flash",
        description="Qwen3.5 全模态轻量模型（文本+图片+视频+音频），262K 上下文。",
        vendor_id="dashscope",
        input_context_window=262_144,
        max_output_tokens=65_536,
        suggested_max_tokens=64_000,
        capabilities=ModelCapabilities(text=True, image=True, video=True, audio=True),
        model_family="qwen-omni",
    ),
    "qwen3.5-omni-flash-2026-03-15": ModelDetail(
        id="qwen3.5-omni-flash-2026-03-15",
        name="Qwen3.5 Omni Flash (2026-03-15)",
        description="Qwen3.5 Omni Flash 快照版本（2026-03-15）。",
        vendor_id="dashscope",
        input_context_window=262_144,
        max_output_tokens=65_536,
        suggested_max_tokens=64_000,
        capabilities=ModelCapabilities(text=True, image=True, video=True, audio=True),
        model_family="qwen-omni",
    ),
    "qwen3.5-omni-plus-realtime": ModelDetail(
        id="qwen3.5-omni-plus-realtime",
        name="Qwen3.5 Omni Plus Realtime",
        description="Qwen3.5 全模态实时对话模型，支持音视频实时交互。",
        vendor_id="dashscope",
        input_context_window=262_144,
        max_output_tokens=65_536,
        suggested_max_tokens=64_000,
        capabilities=ModelCapabilities(text=True, image=True, video=True, audio=True),
        model_family="qwen-omni",
    ),
    "qwen3-max": ModelDetail(
        id="qwen3-max",
        name="Qwen3 Max",
        description="Qwen3 旗舰文本模型，262K 上下文。",
        vendor_id="dashscope",
        input_context_window=262_144,
        max_output_tokens=65_536,
        suggested_max_tokens=64_000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        pricing_input_per_1m=1.2,
        pricing_output_per_1m=6,
        model_family="qwen3",
    ),
    "qwen3-max-2026-01-23": ModelDetail(
        id="qwen3-max-2026-01-23",
        name="Qwen3 Max 2026-01-23",
        description="Qwen3 Max 快照版本（2026-01-23）。",
        vendor_id="dashscope",
        input_context_window=262_144,
        max_output_tokens=65_536,
        suggested_max_tokens=64_000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        pricing_input_per_1m=1.2,
        pricing_output_per_1m=6,
        model_family="qwen3",
    ),
    "qwen3-max-preview": ModelDetail(
        id="qwen3-max-preview",
        name="Qwen3 Max Preview",
        description="Qwen3 Max 预览版本，262K 上下文。",
        vendor_id="dashscope",
        input_context_window=262_144,
        max_output_tokens=65_536,
        suggested_max_tokens=64_000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        pricing_input_per_1m=1.2,
        pricing_output_per_1m=6,
        model_family="qwen3",
    ),
    "qwen3-max-2025-09-23": ModelDetail(
        id="qwen3-max-2025-09-23",
        name="Qwen3 Max 2025-09-23",
        description="Qwen3 Max 快照版本（2025-09-23）。",
        vendor_id="dashscope",
        input_context_window=262_144,
        max_output_tokens=65_536,
        suggested_max_tokens=64_000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        pricing_input_per_1m=1.2,
        pricing_output_per_1m=6,
        model_family="qwen3",
    ),
    "qwen3-coder-plus": ModelDetail(
        id="qwen3-coder-plus",
        name="Qwen3 Coder Plus",
        description="Qwen3 编程模型，1M 上下文，适合复杂编程任务。",
        vendor_id="dashscope",
        input_context_window=1_000_000,
        max_output_tokens=65_536,
        suggested_max_tokens=64_000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        pricing_input_per_1m=1,
        pricing_output_per_1m=5,
        model_family="qwen-coder",
    ),
    "qwen3-coder-plus-2025-09-23": ModelDetail(
        id="qwen3-coder-plus-2025-09-23",
        name="Qwen3 Coder Plus 2025-09-23",
        description="Qwen3 Coder Plus 快照版本（2025-09-23）。",
        vendor_id="dashscope",
        input_context_window=1_000_000,
        max_output_tokens=65_536,
        suggested_max_tokens=64_000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        pricing_input_per_1m=1,
        pricing_output_per_1m=5,
        model_family="qwen-coder",
    ),
    "qwen3-coder-plus-2025-07-22": ModelDetail(
        id="qwen3-coder-plus-2025-07-22",
        name="Qwen3 Coder Plus 2025-07-22",
        description="Qwen3 Coder Plus 快照版本（2025-07-22）。",
        vendor_id="dashscope",
        input_context_window=1_000_000,
        max_output_tokens=65_536,
        suggested_max_tokens=64_000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        pricing_input_per_1m=1,
        pricing_output_per_1m=5,
        model_family="qwen-coder",
    ),
    "qwen3-coder-flash": ModelDetail(
        id="qwen3-coder-flash",
        name="Qwen3 Coder Flash",
        description="Qwen3 高速编程模型，1M 上下文。",
        vendor_id="dashscope",
        input_context_window=1_000_000,
        max_output_tokens=65_536,
        suggested_max_tokens=64_000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        pricing_input_per_1m=0.3,
        pricing_output_per_1m=1.5,
        model_family="qwen-coder",
    ),
    "qwen3-coder-flash-2025-07-28": ModelDetail(
        id="qwen3-coder-flash-2025-07-28",
        name="Qwen3 Coder Flash 2025-07-28",
        description="Qwen3 Coder Flash 快照版本（2025-07-28）。",
        vendor_id="dashscope",
        input_context_window=1_000_000,
        max_output_tokens=65_536,
        suggested_max_tokens=64_000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        pricing_input_per_1m=0.3,
        pricing_output_per_1m=1.5,
        model_family="qwen-coder",
    ),
    "qwen3-coder-next": ModelDetail(
        id="qwen3-coder-next",
        name="Qwen3 Coder Next",
        description="Qwen3 下一代编程模型，262K 上下文。",
        vendor_id="dashscope",
        input_context_window=262_144,
        max_output_tokens=65_536,
        suggested_max_tokens=64_000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        model_family="qwen-coder",
    ),
    "qwen3-coder-480b-a35b-instruct": ModelDetail(
        id="qwen3-coder-480b-a35b-instruct",
        name="Qwen3 Coder 480B A35B Instruct",
        description="Qwen3 Coder 开源 480B-A35B 指令模型，262K 上下文。",
        vendor_id="dashscope",
        input_context_window=262_144,
        max_output_tokens=65_536,
        suggested_max_tokens=64_000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        pricing_input_per_1m=1.5,
        pricing_output_per_1m=7.5,
        model_family="qwen-coder",
    ),
    "qwen3-coder-30b-a3b-instruct": ModelDetail(
        id="qwen3-coder-30b-a3b-instruct",
        name="Qwen3 Coder 30B A3B Instruct",
        description="Qwen3 Coder 开源 30B-A3B 指令模型，262K 上下文。",
        vendor_id="dashscope",
        input_context_window=262_144,
        max_output_tokens=65_536,
        suggested_max_tokens=64_000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        pricing_input_per_1m=0.45,
        pricing_output_per_1m=2.25,
        model_family="qwen-coder",
    ),
    "qwen3-235b-a22b": ModelDetail(
        id="qwen3-235b-a22b",
        name="Qwen3 235B A22B",
        description="Qwen3 开源 MoE 模型（235B 总参/22B 激活），131K 上下文。",
        vendor_id="dashscope",
        input_context_window=131_072,
        max_output_tokens=16_384,
        suggested_max_tokens=16_000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        pricing_input_per_1m=0.7,
        pricing_output_per_1m=2.8,
        model_family="qwen3",
    ),
    "qwen3-235b-a22b-instruct-2507": ModelDetail(
        id="qwen3-235b-a22b-instruct-2507",
        name="Qwen3 235B A22B Instruct 2507",
        description="Qwen3 235B 指令快照版本（2507），131K 上下文。",
        vendor_id="dashscope",
        input_context_window=131_072,
        max_output_tokens=32_768,
        suggested_max_tokens=32_000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        model_family="qwen3",
    ),
    "qwen3-235b-a22b-thinking-2507": ModelDetail(
        id="qwen3-235b-a22b-thinking-2507",
        name="Qwen3 235B A22B Thinking 2507",
        description="Qwen3 235B 推理快照版本（2507），131K 上下文。",
        vendor_id="dashscope",
        input_context_window=131_072,
        max_output_tokens=32_768,
        suggested_max_tokens=32_000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        model_family="qwen3",
    ),
    "qwen3-next-80b-a3b-thinking": ModelDetail(
        id="qwen3-next-80b-a3b-thinking",
        name="Qwen3 Next 80B A3B Thinking",
        description="Qwen3 Next 80B 推理模型，131K 上下文。",
        vendor_id="dashscope",
        input_context_window=131_072,
        max_output_tokens=32_768,
        suggested_max_tokens=32_000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        pricing_input_per_1m=0.5,
        pricing_output_per_1m=6,
        model_family="qwen3",
    ),
    "qwen3-next-80b-a3b-instruct": ModelDetail(
        id="qwen3-next-80b-a3b-instruct",
        name="Qwen3 Next 80B A3B Instruct",
        description="Qwen3 Next 80B 指令模型，131K 上下文。",
        vendor_id="dashscope",
        input_context_window=131_072,
        max_output_tokens=32_768,
        suggested_max_tokens=32_000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        pricing_input_per_1m=0.5,
        pricing_output_per_1m=2,
        model_family="qwen3",
    ),
    "qwen3-32b": ModelDetail(
        id="qwen3-32b",
        name="Qwen3 32B",
        description="Qwen3 开源 32B 文本模型，131K 上下文。",
        vendor_id="dashscope",
        input_context_window=131_072,
        max_output_tokens=16_384,
        suggested_max_tokens=16_000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        pricing_input_per_1m=0.7,
        pricing_output_per_1m=2.8,
        model_family="qwen3",
    ),
    "qwen3-30b-a3b": ModelDetail(
        id="qwen3-30b-a3b",
        name="Qwen3 30B A3B",
        description="Qwen3 开源 30B-A3B 文本模型，131K 上下文。",
        vendor_id="dashscope",
        input_context_window=131_072,
        max_output_tokens=16_384,
        suggested_max_tokens=16_000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        model_family="qwen3",
    ),
    "qwen3-30b-a3b-instruct-2507": ModelDetail(
        id="qwen3-30b-a3b-instruct-2507",
        name="Qwen3 30B A3B Instruct 2507",
        description="Qwen3 30B-A3B 指令快照版本（2507），131K 上下文。",
        vendor_id="dashscope",
        input_context_window=131_072,
        max_output_tokens=32_768,
        suggested_max_tokens=32_000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        model_family="qwen3",
    ),
    "qwen3-30b-a3b-thinking-2507": ModelDetail(
        id="qwen3-30b-a3b-thinking-2507",
        name="Qwen3 30B A3B Thinking 2507",
        description="Qwen3 30B-A3B 推理快照版本（2507），131K 上下文。",
        vendor_id="dashscope",
        input_context_window=131_072,
        max_output_tokens=32_768,
        suggested_max_tokens=32_000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        model_family="qwen3",
    ),
    "qwen3-14b": ModelDetail(
        id="qwen3-14b",
        name="Qwen3 14B",
        description="Qwen3 开源 14B 文本模型，131K 上下文。",
        vendor_id="dashscope",
        input_context_window=131_072,
        max_output_tokens=8_192,
        suggested_max_tokens=8_000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        pricing_input_per_1m=0.35,
        pricing_output_per_1m=1.4,
        model_family="qwen3",
    ),
    "qwen3-8b": ModelDetail(
        id="qwen3-8b",
        name="Qwen3 8B",
        description="Qwen3 开源 8B 文本模型，131K 上下文。",
        vendor_id="dashscope",
        input_context_window=131_072,
        max_output_tokens=8_192,
        suggested_max_tokens=8_000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        pricing_input_per_1m=0.18,
        pricing_output_per_1m=0.7,
        model_family="qwen3",
    ),
    "qwen3-4b": ModelDetail(
        id="qwen3-4b",
        name="Qwen3 4B",
        description="Qwen3 开源 4B 文本模型，131K 上下文。",
        vendor_id="dashscope",
        input_context_window=131_072,
        max_output_tokens=8_192,
        suggested_max_tokens=8_000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        model_family="qwen3",
    ),
    "qwen3-1.7b": ModelDetail(
        id="qwen3-1.7b",
        name="Qwen3 1.7B",
        description="Qwen3 开源 1.7B 文本模型，32K 上下文。",
        vendor_id="dashscope",
        input_context_window=32_768,
        max_output_tokens=8_192,
        suggested_max_tokens=8_000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        model_family="qwen3",
    ),
    "qwen3-0.6b": ModelDetail(
        id="qwen3-0.6b",
        name="Qwen3 0.6B",
        description="Qwen3 开源 0.6B 文本模型，32K 上下文。",
        vendor_id="dashscope",
        input_context_window=32_768,
        max_output_tokens=8_192,
        suggested_max_tokens=8_000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        model_family="qwen3",
    ),
    "qwen-flash": ModelDetail(
        id="qwen-flash",
        name="Qwen Flash",
        description="Qwen 高速文本模型，1M 超长上下文，适合低延迟任务。",
        vendor_id="dashscope",
        input_context_window=1_000_000,
        max_output_tokens=32_768,
        suggested_max_tokens=32_000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        pricing_input_per_1m=0.05,
        pricing_output_per_1m=0.4,
        model_family="qwen",
    ),
    "qwen-plus": ModelDetail(
        id="qwen-plus",
        name="Qwen Plus",
        description="Qwen 主力文本模型，平衡性能与成本，适合日常研究对话。",
        vendor_id="dashscope",
        input_context_window=1_000_000,
        max_output_tokens=32_768,
        suggested_max_tokens=32_000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        pricing_input_per_1m=0.4,
        pricing_output_per_1m=1.2,
        recommended=True,
        model_family="qwen",
    ),
    "qwen-plus-0419": ModelDetail(
        id="qwen-plus-0419",
        name="Qwen Plus 0419",
        description="Qwen Plus 快照版本（0419），长上下文。",
        vendor_id="dashscope",
        input_context_window=1_000_000,
        max_output_tokens=16_384,
        suggested_max_tokens=16_384,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        model_family="qwen",
    ),
    "qwen-max": ModelDetail(
        id="qwen-max",
        name="Qwen Max",
        description="Qwen 最强文本模型，适合复杂推理、深度分析和长文档理解。",
        vendor_id="dashscope",
        input_context_window=32_768,
        max_output_tokens=8_192,
        suggested_max_tokens=8_192,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        pricing_input_per_1m=1.6,
        pricing_output_per_1m=6.4,
        model_family="qwen",
    ),
    "qwen-turbo": ModelDetail(
        id="qwen-turbo",
        name="Qwen Turbo",
        description="Qwen 轻量快速模型，适合简单问答、摘要、分类等低延迟场景。",
        vendor_id="dashscope",
        input_context_window=1_000_000,
        max_output_tokens=16_384,
        suggested_max_tokens=4_096,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        pricing_input_per_1m=0.05,
        pricing_output_per_1m=0.2,
        model_family="qwen",
    ),
    "qwen-turbo-0419": ModelDetail(
        id="qwen-turbo-0419",
        name="Qwen Turbo 0419",
        description="Qwen Turbo 快照版本（0419），响应极快。",
        vendor_id="dashscope",
        input_context_window=1_000_000,
        max_output_tokens=4_096,
        suggested_max_tokens=4_096,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        model_family="qwen",
    ),
    "qwq-plus": ModelDetail(
        id="qwq-plus",
        name="QWQ Plus",
        description="新一代推理模型，更强的思维链与复杂推理能力。",
        vendor_id="dashscope",
        input_context_window=131_072,
        max_output_tokens=8_192,
        suggested_max_tokens=8_192,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        pricing_input_per_1m=0.8,
        pricing_output_per_1m=2.4,
        model_family="qwq",
    ),
    "qwq-32b": ModelDetail(
        id="qwq-32b",
        name="QWQ 32B",
        description="开源推理增强模型（类 o1），擅长数学、逻辑和多步推理。",
        vendor_id="dashscope",
        input_context_window=131_072,
        max_output_tokens=8_192,
        suggested_max_tokens=8_192,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        model_family="qwq",
    ),
    "qwen-vl-max": ModelDetail(
        id="qwen-vl-max",
        name="Qwen VL Max",
        description="最强视觉语言模型，支持图像理解、图表提取、OCR。",
        vendor_id="dashscope",
        input_context_window=131_072,
        max_output_tokens=8_192,
        suggested_max_tokens=8_192,
        capabilities=ModelCapabilities(text=True, image=True, video=False, audio=False),
        pricing_input_per_1m=0.8,
        pricing_output_per_1m=3.2,
        model_family="qwen-vl",
    ),
    "qwen-vl-max-0319": ModelDetail(
        id="qwen-vl-max-0319",
        name="Qwen VL Max 0319",
        description="Qwen VL Max 快照版本（0319），支持图像与视频理解。",
        vendor_id="dashscope",
        input_context_window=131_072,
        max_output_tokens=8_192,
        suggested_max_tokens=8_192,
        capabilities=ModelCapabilities(text=True, image=True, video=True, audio=False),
        model_family="qwen-vl",
    ),
    "qwen-vl-plus": ModelDetail(
        id="qwen-vl-plus",
        name="Qwen VL Plus",
        description="视觉语言模型，支持图文理解，性价比高。",
        vendor_id="dashscope",
        input_context_window=131_072,
        max_output_tokens=8_192,
        suggested_max_tokens=8_192,
        capabilities=ModelCapabilities(text=True, image=True, video=False, audio=False),
        pricing_input_per_1m=0.21,
        pricing_output_per_1m=0.63,
        model_family="qwen-vl",
    ),
    "qwen-vl-ocr": ModelDetail(
        id="qwen-vl-ocr",
        name="Qwen VL OCR",
        description="专注于 OCR 识别和文档数字化的视觉模型。",
        vendor_id="dashscope",
        input_context_window=34_096,
        max_output_tokens=4_096,
        suggested_max_tokens=4_096,
        capabilities=ModelCapabilities(text=True, image=True, video=False, audio=False),
        pricing_input_per_1m=0.72,
        pricing_output_per_1m=0.72,
        model_family="qwen-vl",
    ),
    "qwen3-vl-plus": ModelDetail(
        id="qwen3-vl-plus",
        name="Qwen3 VL Plus",
        description="Qwen3 视觉语言旗舰模型，支持函数调用与图像视频理解。",
        vendor_id="dashscope",
        input_context_window=262_144,
        max_output_tokens=32_768,
        suggested_max_tokens=32_000,
        capabilities=ModelCapabilities(text=True, image=True, video=True, audio=False),
        pricing_input_per_1m=0.2,
        pricing_output_per_1m=1.6,
        model_family="qwen3-vl",
    ),
    "qwen3-vl-flash": ModelDetail(
        id="qwen3-vl-flash",
        name="Qwen3 VL Flash",
        description="Qwen3 高速视觉语言模型，支持函数调用与图像视频理解。",
        vendor_id="dashscope",
        input_context_window=262_144,
        max_output_tokens=32_768,
        suggested_max_tokens=32_000,
        capabilities=ModelCapabilities(text=True, image=True, video=True, audio=False),
        model_family="qwen3-vl",
    ),
    "qwen3-vl-235b-a22b-instruct": ModelDetail(
        id="qwen3-vl-235b-a22b-instruct",
        name="Qwen3 VL 235B A22B Instruct",
        description="Qwen3 VL 开源 MoE 视觉指令模型，131K 上下文。",
        vendor_id="dashscope",
        input_context_window=131_072,
        max_output_tokens=32_768,
        suggested_max_tokens=8_000,
        capabilities=ModelCapabilities(text=True, image=True, video=True, audio=False),
        pricing_input_per_1m=0.7,
        pricing_output_per_1m=2.8,
        model_family="qwen3-vl",
    ),
    "qwen3-vl-32b-instruct": ModelDetail(
        id="qwen3-vl-32b-instruct",
        name="Qwen3 VL 32B Instruct",
        description="Qwen3 VL 开源 32B 视觉指令模型，131K 上下文。",
        vendor_id="dashscope",
        input_context_window=131_072,
        max_output_tokens=32_768,
        suggested_max_tokens=8_000,
        capabilities=ModelCapabilities(text=True, image=True, video=True, audio=False),
        model_family="qwen3-vl",
    ),
    "qwen3-vl-30b-a3b-instruct": ModelDetail(
        id="qwen3-vl-30b-a3b-instruct",
        name="Qwen3 VL 30B A3B Instruct",
        description="Qwen3 VL 开源 30B-A3B 视觉指令模型，131K 上下文。",
        vendor_id="dashscope",
        input_context_window=131_072,
        max_output_tokens=32_768,
        suggested_max_tokens=8_000,
        capabilities=ModelCapabilities(text=True, image=True, video=True, audio=False),
        pricing_input_per_1m=0.2,
        pricing_output_per_1m=0.8,
        model_family="qwen3-vl",
    ),
    "qwen3-vl-8b-instruct": ModelDetail(
        id="qwen3-vl-8b-instruct",
        name="Qwen3 VL 8B Instruct",
        description="Qwen3 VL 开源 8B 视觉指令模型，轻量部署。",
        vendor_id="dashscope",
        input_context_window=131_072,
        max_output_tokens=32_768,
        suggested_max_tokens=8_000,
        capabilities=ModelCapabilities(text=True, image=True, video=True, audio=False),
        model_family="qwen3-vl",
    ),
    "qwen2.5-vl-72b-instruct": ModelDetail(
        id="qwen2.5-vl-72b-instruct",
        name="Qwen2.5 VL 72B Instruct",
        description="Qwen2.5 VL 开源 72B 视觉语言模型，支持图像与视频理解。",
        vendor_id="dashscope",
        input_context_window=128_000,
        max_output_tokens=8_192,
        suggested_max_tokens=8_000,
        capabilities=ModelCapabilities(text=True, image=True, video=True, audio=False),
        pricing_input_per_1m=2.8,
        pricing_output_per_1m=8.4,
        model_family="qwen2.5-vl",
    ),
    "qwen2.5-vl-32b-instruct": ModelDetail(
        id="qwen2.5-vl-32b-instruct",
        name="Qwen2.5 VL 32B Instruct",
        description="Qwen2.5 VL 开源 32B 视觉语言模型，支持图像与视频理解。",
        vendor_id="dashscope",
        input_context_window=128_000,
        max_output_tokens=8_192,
        suggested_max_tokens=8_000,
        capabilities=ModelCapabilities(text=True, image=True, video=True, audio=False),
        model_family="qwen2.5-vl",
    ),
    "qwen2.5-vl-7b-instruct": ModelDetail(
        id="qwen2.5-vl-7b-instruct",
        name="Qwen2.5 VL 7B Instruct",
        description="Qwen2.5 VL 开源 7B 视觉语言模型，轻量部署。",
        vendor_id="dashscope",
        input_context_window=128_000,
        max_output_tokens=8_192,
        suggested_max_tokens=8_000,
        capabilities=ModelCapabilities(text=True, image=True, video=True, audio=False),
        pricing_input_per_1m=0.35,
        pricing_output_per_1m=1.05,
        model_family="qwen2.5-vl",
    ),
    "qwen2.5-vl-3b-instruct": ModelDetail(
        id="qwen2.5-vl-3b-instruct",
        name="Qwen2.5 VL 3B Instruct",
        description="Qwen2.5 VL 开源 3B 视觉语言模型，极致轻量。",
        vendor_id="dashscope",
        input_context_window=128_000,
        max_output_tokens=8_192,
        suggested_max_tokens=8_000,
        capabilities=ModelCapabilities(text=True, image=True, video=True, audio=False),
        model_family="qwen2.5-vl",
    ),
    "qwen2.5-72b-instruct": ModelDetail(
        id="qwen2.5-72b-instruct",
        name="Qwen2.5 72B Instruct",
        description="Qwen2.5 开源 72B 文本模型，适合大规模文本生成。",
        vendor_id="dashscope",
        input_context_window=32_768,
        max_output_tokens=8_192,
        suggested_max_tokens=8_000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        pricing_input_per_1m=1.4,
        pricing_output_per_1m=5.6,
        model_family="qwen2.5",
    ),
    "qwen2.5-32b-instruct": ModelDetail(
        id="qwen2.5-32b-instruct",
        name="Qwen2.5 32B Instruct",
        description="Qwen2.5 开源 32B 文本模型，性能均衡。",
        vendor_id="dashscope",
        input_context_window=32_768,
        max_output_tokens=8_192,
        suggested_max_tokens=8_000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        pricing_input_per_1m=0.7,
        pricing_output_per_1m=2.8,
        model_family="qwen2.5",
    ),
    "qwen2.5-14b-instruct": ModelDetail(
        id="qwen2.5-14b-instruct",
        name="Qwen2.5 14B Instruct",
        description="Qwen2.5 开源 14B 文本模型，轻量部署首选。",
        vendor_id="dashscope",
        input_context_window=32_768,
        max_output_tokens=8_192,
        suggested_max_tokens=8_000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        pricing_input_per_1m=0.35,
        pricing_output_per_1m=1.4,
        model_family="qwen2.5",
    ),
    "qwen2.5-14b-instruct-1m": ModelDetail(
        id="qwen2.5-14b-instruct-1m",
        name="Qwen2.5 14B Instruct 1M",
        description="Qwen2.5 14B 长上下文文本模型，1M 上下文。",
        vendor_id="dashscope",
        input_context_window=1_000_000,
        max_output_tokens=8_192,
        suggested_max_tokens=8_000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        model_family="qwen2.5",
    ),
    "qwen2.5-7b-instruct": ModelDetail(
        id="qwen2.5-7b-instruct",
        name="Qwen2.5 7B Instruct",
        description="Qwen2.5 开源 7B 文本模型，32K 上下文。",
        vendor_id="dashscope",
        input_context_window=32_768,
        max_output_tokens=8_192,
        suggested_max_tokens=8_000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        pricing_input_per_1m=0.17,
        pricing_output_per_1m=0.7,
        model_family="qwen2.5",
    ),
    "qwen2.5-7b-instruct-1m": ModelDetail(
        id="qwen2.5-7b-instruct-1m",
        name="Qwen2.5 7B Instruct 1M",
        description="Qwen2.5 7B 长上下文文本模型，1M 上下文。",
        vendor_id="dashscope",
        input_context_window=1_000_000,
        max_output_tokens=8_192,
        suggested_max_tokens=8_000,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        model_family="qwen2.5",
    ),
    "qwen-omni-turbo": ModelDetail(
        id="qwen-omni-turbo",
        name="Qwen Omni Turbo",
        description="全模态模型（文本+图片+视频+音频），适合多模态交互场景。",
        vendor_id="dashscope",
        input_context_window=32_768,
        max_output_tokens=2_048,
        suggested_max_tokens=2_048,
        capabilities=ModelCapabilities(text=True, image=True, video=True, audio=True),
        pricing_input_per_1m=0.07,
        pricing_output_per_1m=0.27,
        model_family="qwen-omni",
    ),
    "qwen2-audio": ModelDetail(
        id="qwen2-audio",
        name="Qwen2 Audio",
        description="语音理解模型，支持语音识别、语音对话与音频分析。",
        vendor_id="dashscope",
        input_context_window=32_768,
        max_output_tokens=4_096,
        suggested_max_tokens=4_096,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=True),
        model_family="qwen-audio",
    ),
    "fun-asr": ModelDetail(
        id="fun-asr",
        name="fun-asr",
        description="阿里云语音识别模型。",
        vendor_id="dashscope",
        input_context_window=32_768,
        max_output_tokens=1,
        suggested_max_tokens=1,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=True),
        model_family="fun-asr",
    ),
    "fun-asr-realtime": ModelDetail(
        id="fun-asr-realtime",
        name="fun-asr-realtime",
        description="阿里云实时语音识别模型。",
        vendor_id="dashscope",
        input_context_window=32_768,
        max_output_tokens=1,
        suggested_max_tokens=1,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=True),
        model_family="fun-asr",
    ),
    "fun-music-v1": ModelDetail(
        id="fun-music-v1",
        name="fun-music-v1",
        description="阿里云 AI 音乐生成模型。",
        vendor_id="dashscope",
        input_context_window=1,
        max_output_tokens=1,
        suggested_max_tokens=1,
        capabilities=ModelCapabilities(text=False, image=False, video=False, audio=True),
        model_family="fun-music",
    ),
    "text-embedding-v4": ModelDetail(
        id="text-embedding-v4",
        name="text-embedding-v4",
        description="阿里云文本向量化模型。",
        vendor_id="dashscope",
        input_context_window=8_192,
        max_output_tokens=1,
        suggested_max_tokens=1,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        model_family="embedding",
    ),
    "tongyi-embedding-vision-plus": ModelDetail(
        id="tongyi-embedding-vision-plus",
        name="tongyi-embedding-vision-plus",
        description="阿里云多模态向量化模型。",
        vendor_id="dashscope",
        input_context_window=16_384,
        max_output_tokens=1,
        suggested_max_tokens=1,
        capabilities=ModelCapabilities(text=True, image=True, video=False, audio=False),
        model_family="embedding",
    ),
    "qwen3-rerank": ModelDetail(
        id="qwen3-rerank",
        name="qwen3-rerank",
        description="阿里云 Qwen3 重排序模型。",
        vendor_id="dashscope",
        input_context_window=16_384,
        max_output_tokens=1,
        suggested_max_tokens=1,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        model_family="embedding",
    ),
    "wan2.7-image-pro": ModelDetail(
        id="wan2.7-image-pro",
        name="wan2.7-image-pro",
        description="阿里云万相文生图模型。",
        vendor_id="dashscope",
        input_context_window=1,
        max_output_tokens=1,
        suggested_max_tokens=1,
        capabilities=ModelCapabilities(text=True, image=True, video=False, audio=False),
        model_family="wan",
    ),
    "qwen-image-3.0-pro": ModelDetail(
        id="qwen-image-3.0-pro",
        name="qwen-image-3.0-pro",
        description="阿里云 Qwen 文生图模型（3.0 Pro）。",
        vendor_id="dashscope",
        input_context_window=1,
        max_output_tokens=1,
        suggested_max_tokens=1,
        capabilities=ModelCapabilities(text=True, image=True, video=False, audio=False),
        model_family="wan",
    ),
    "qwen-audio-3.0-tts-plus": ModelDetail(
        id="qwen-audio-3.0-tts-plus",
        name="qwen-audio-3.0-tts-plus",
        description="阿里云 Qwen Audio 3.0 语音合成模型。",
        vendor_id="dashscope",
        input_context_window=1,
        max_output_tokens=1,
        suggested_max_tokens=1,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=True),
        model_family="qwen-audio",
    ),
    "qwen-audio-3.0-asr-flash-streaming": ModelDetail(
        id="qwen-audio-3.0-asr-flash-streaming",
        name="qwen-audio-3.0-asr-flash-streaming",
        description="阿里云 Qwen Audio 3.0 流式语音识别模型。",
        vendor_id="dashscope",
        input_context_window=1,
        max_output_tokens=1,
        suggested_max_tokens=1,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=True),
        model_family="qwen-audio",
    ),
    "qwen-audio-3.0-asr-flash-filetrans": ModelDetail(
        id="qwen-audio-3.0-asr-flash-filetrans",
        name="qwen-audio-3.0-asr-flash-filetrans",
        description="阿里云 Qwen Audio 3.0 文件语音识别模型。",
        vendor_id="dashscope",
        input_context_window=1,
        max_output_tokens=1,
        suggested_max_tokens=1,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=True),
        model_family="qwen-audio",
    ),
    "qwen-audio-3.0-realtime-plus": ModelDetail(
        id="qwen-audio-3.0-realtime-plus",
        name="qwen-audio-3.0-realtime-plus",
        description="阿里云 Qwen Audio 3.0 实时语音对话模型。",
        vendor_id="dashscope",
        input_context_window=1,
        max_output_tokens=1,
        suggested_max_tokens=1,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=True),
        model_family="qwen-audio",
    ),
    "deepseek-v4-flash-0731": ModelDetail(
        id="deepseek-v4-flash-0731",
        name="DeepSeek V4 Flash 0731",
        description="DeepSeek V4 Flash（0731 检查点），1M 上下文，第三方直供。",
        vendor_id="dashscope",
        input_context_window=1_000_000,
        max_output_tokens=384_000,
        suggested_max_tokens=32_768,
        capabilities=ModelCapabilities(text=True, image=False, video=False, audio=False),
        pricing_input_per_1m=0.2,
        pricing_output_per_1m=0.4,
        model_family="deepseek",
    ),
    "kimi/kimi-k3": ModelDetail(
        id="kimi/kimi-k3",
        name="Kimi K3",
        description="Kimi 旗舰模型，1M 上下文，原生支持视觉理解，第三方直供。",
        vendor_id="dashscope",
        input_context_window=1_048_576,
        max_output_tokens=131_072,
        suggested_max_tokens=32_768,
        capabilities=ModelCapabilities(text=True, image=True, video=True, audio=False),
        pricing_input_per_1m=3,
        pricing_output_per_1m=15,
        recommended=True,
        model_family="kimi",
    ),
}


def register(target: dict[str, ModelDetail]) -> None:
    """Merge Qwen/DashScope models into the target repository dictionary."""
    target.update(MODELS)
