"""ZhipuAI (GLM) model data provider."""

from __future__ import annotations

from app.model_info.schemas import ModelCapabilities, ModelDetail

MODELS: dict[str, ModelDetail] = {
    "glm-4-plus": ModelDetail(
        id="glm-4-plus",
        name="GLM-4 Plus",
        description="智谱 AI GLM-4 旗舰模型，支持 128K 上下文。",
        vendor_id="zhipu",
        input_context_window=128_000,
        max_output_tokens=8_192,
        suggested_max_tokens=8_192,
        capabilities=ModelCapabilities(text=True),
        recommended=True,
        model_family="glm-4",
    ),
    "glm-4-flash": ModelDetail(
        id="glm-4-flash",
        name="GLM-4 Flash",
        description="智谱 AI GLM-4 轻量快速模型，响应速度快。",
        vendor_id="zhipu",
        input_context_window=128_000,
        max_output_tokens=4_096,
        suggested_max_tokens=4_096,
        capabilities=ModelCapabilities(text=True),
        model_family="glm-4",
    ),
    "glm-4v-plus": ModelDetail(
        id="glm-4v-plus",
        name="GLM-4V Plus",
        description="智谱 AI GLM-4V 多模态模型，支持图片理解。",
        vendor_id="zhipu",
        input_context_window=128_000,
        max_output_tokens=4_096,
        suggested_max_tokens=4_096,
        capabilities=ModelCapabilities(text=True, image=True),
        model_family="glm-4v",
    ),
    # -- GLM-5.2 --
    "glm-5.2": ModelDetail(
        id="glm-5.2",
        name="GLM-5.2",
        description="智谱 AI GLM-5.2 最新旗舰模型，1M 无损上下文，支持图像理解。",
        vendor_id="zhipu",
        input_context_window=1_000_000,
        max_output_tokens=128_000,
        suggested_max_tokens=128_000,
        capabilities=ModelCapabilities(text=True, image=True),
        knowledge_cutoff="2026-06",
        recommended=True,
        model_family="glm-4",
    ),
    # -- GLM-5.1 --
    "glm-5.1": ModelDetail(
        id="glm-5.1",
        name="GLM-5.1",
        description="智谱 AI GLM-5.1 高性能模型，200K 上下文，擅长复杂代码与长程任务。",
        vendor_id="zhipu",
        input_context_window=200_000,
        max_output_tokens=128_000,
        suggested_max_tokens=128_000,
        capabilities=ModelCapabilities(text=True),
        knowledge_cutoff="2026-06",
        recommended=True,
        model_family="glm-4",
    ),
    # -- GLM-5 --
    "glm-5": ModelDetail(
        id="glm-5",
        name="GLM-5",
        description="智谱 AI GLM-5 旗舰模型，200K 上下文，擅长 Agentic 长程规划与执行。",
        vendor_id="zhipu",
        input_context_window=200_000,
        max_output_tokens=128_000,
        suggested_max_tokens=128_000,
        capabilities=ModelCapabilities(text=True),
        knowledge_cutoff="2026-05",
        recommended=False,
        model_family="glm-4",
    ),
    # -- GLM-5-Turbo --
    "glm-5-turbo": ModelDetail(
        id="glm-5-turbo",
        name="GLM-5 Turbo",
        description="智谱 AI GLM-5-Turbo，性能与 GLM-5 对齐的高速版，200K 上下文。",
        vendor_id="zhipu",
        input_context_window=200_000,
        max_output_tokens=131_072,
        suggested_max_tokens=65_536,
        capabilities=ModelCapabilities(text=True),
        knowledge_cutoff="2026-06",
        recommended=True,
        model_family="glm-5",
    ),
    # -- GLM-4.7 --
    "glm-4.7": ModelDetail(
        id="glm-4.7",
        name="GLM-4.7",
        description="智谱 AI GLM-4.7 通用对话、推理与智能体能力全面升级，200K 上下文。",
        vendor_id="zhipu",
        input_context_window=200_000,
        max_output_tokens=128_000,
        suggested_max_tokens=128_000,
        capabilities=ModelCapabilities(text=True),
        knowledge_cutoff="2026-04",
        recommended=False,
        model_family="glm-4",
    ),
    # -- GLM-4.6 --
    "glm-4.6": ModelDetail(
        id="glm-4.6",
        name="GLM-4.6",
        description="智谱 AI GLM-4.6 高级编码、复杂推理与工具调用，200K 上下文。",
        vendor_id="zhipu",
        input_context_window=200_000,
        max_output_tokens=128_000,
        suggested_max_tokens=128_000,
        capabilities=ModelCapabilities(text=True),
        knowledge_cutoff="2026-03",
        recommended=False,
        model_family="glm-4",
    ),
    # -- GLM-4.5 series --
    "glm-4.5": ModelDetail(
        id="glm-4.5",
        name="GLM-4.5",
        description="智谱 AI GLM-4.5 模型，128K 上下文，支持思考模式与工具调用。",
        vendor_id="zhipu",
        input_context_window=128_000,
        max_output_tokens=98_304,
        suggested_max_tokens=65_536,
        capabilities=ModelCapabilities(text=True),
        knowledge_cutoff="2025-06",
        recommended=True,
        model_family="glm-4.5",
    ),
    "glm-4.5-air": ModelDetail(
        id="glm-4.5-air",
        name="GLM-4.5 Air",
        description="智谱 AI GLM-4.5-Air 轻量版，128K 上下文，兼顾性能与成本。",
        vendor_id="zhipu",
        input_context_window=128_000,
        max_output_tokens=98_304,
        suggested_max_tokens=65_536,
        capabilities=ModelCapabilities(text=True),
        knowledge_cutoff="2025-06",
        recommended=False,
        model_family="glm-4.5",
    ),
    "glm-4.5-flash": ModelDetail(
        id="glm-4.5-flash",
        name="GLM-4.5 Flash",
        description="智谱 AI GLM-4.5-Flash 免费模型，128K 上下文，支持思考模式。",
        vendor_id="zhipu",
        input_context_window=128_000,
        max_output_tokens=98_304,
        suggested_max_tokens=65_536,
        capabilities=ModelCapabilities(text=True),
        knowledge_cutoff="2025-06",
        recommended=False,
        model_family="glm-4.5",
    ),
    # -- GLM-4-Long --
    "glm-4-long": ModelDetail(
        id="glm-4-long",
        name="GLM-4 Long",
        description="智谱 AI GLM-4-Long 超长文本模型，支持 1M 上下文。",
        vendor_id="zhipu",
        input_context_window=1_000_000,
        max_output_tokens=4_096,
        suggested_max_tokens=4_096,
        capabilities=ModelCapabilities(text=True),
        model_family="glm-4",
    ),
    # -- GLM-4-Flash-250414 --
    "glm-4-flash-250414": ModelDetail(
        id="glm-4-flash-250414",
        name="GLM-4 Flash 250414",
        description="智谱 AI GLM-4-Flash-250414 免费模型，支持长上下文处理。",
        vendor_id="zhipu",
        input_context_window=128_000,
        max_output_tokens=32_768,
        suggested_max_tokens=32_768,
        capabilities=ModelCapabilities(text=True),
        recommended=False,
        model_family="glm-4",
    ),
    # -- GLM-5V-Turbo --
    "glm-5v-turbo": ModelDetail(
        id="glm-5v-turbo",
        name="GLM-5V Turbo",
        description="智谱 AI GLM-5V-Turbo 多模态 Coding 模型，兼顾视觉理解、推理与代码生成。",
        vendor_id="zhipu",
        input_context_window=200_000,
        max_output_tokens=128_000,
        suggested_max_tokens=128_000,
        capabilities=ModelCapabilities(text=True, image=True),
        knowledge_cutoff="2026-06",
        recommended=True,
        model_family="glm-4v",
    ),
    # -- GLM-4.6V --
    "glm-4.6v": ModelDetail(
        id="glm-4.6v",
        name="GLM-4.6V",
        description="智谱 AI GLM-4.6V 视觉推理模型，原生支持工具调用与长上下文。",
        vendor_id="zhipu",
        input_context_window=128_000,
        max_output_tokens=32_768,
        suggested_max_tokens=32_768,
        capabilities=ModelCapabilities(text=True, image=True),
        knowledge_cutoff="2026-03",
        recommended=False,
        model_family="glm-4v",
    ),
    # -- GLM-4.6V Flash / FlashX --
    "glm-4.6v-flash": ModelDetail(
        id="glm-4.6v-flash",
        name="GLM-4.6V Flash",
        description="智谱 AI GLM-4.6V-Flash 免费视觉模型，128K 上下文，原生工具调用。",
        vendor_id="zhipu",
        input_context_window=128_000,
        max_output_tokens=32_768,
        suggested_max_tokens=16_384,
        capabilities=ModelCapabilities(text=True, image=True),
        knowledge_cutoff="2025-12",
        recommended=False,
        model_family="glm-4v",
    ),
    "glm-4.6v-flashx": ModelDetail(
        id="glm-4.6v-flashx",
        name="GLM-4.6V FlashX",
        description="智谱 AI GLM-4.6V-FlashX 轻量高速视觉模型，128K 上下文。",
        vendor_id="zhipu",
        input_context_window=128_000,
        max_output_tokens=32_768,
        suggested_max_tokens=16_384,
        capabilities=ModelCapabilities(text=True, image=True),
        knowledge_cutoff="2025-12",
        recommended=False,
        model_family="glm-4v",
    ),
    # -- GLM-4V-Flash --
    "glm-4v-flash": ModelDetail(
        id="glm-4v-flash",
        name="GLM-4V Flash",
        description="智谱 AI GLM-4V-Flash 免费模型，支持基础图像理解。",
        vendor_id="zhipu",
        input_context_window=16_000,
        max_output_tokens=1_024,
        suggested_max_tokens=1_024,
        capabilities=ModelCapabilities(text=True, image=True),
        recommended=False,
        model_family="glm-4v",
    ),
}

def register(target: dict[str, ModelDetail]) -> None:
    """Merge ZhipuAI models into the target repository dictionary."""
    target.update(MODELS)
