export {
  parseVlmJsonObject,
  ChartExtractionError,
  CHART_DATA_COLUMNS,
  CHART_DATA_POINTS_COLUMNS,
  normalizeChartJson,
  parseVlmJson,
  VLM_PROMPT,
  type ChartPointRow,
  type ChartRow,
  type NormalizeChartOptions,
} from "./chart-json.js";
export {
  CHART_CSV_NAME,
  CHART_POINTS_CSV_NAME,
  validateChartData,
  validateChartExtraction,
  writeChartCsvs,
} from "./chart-csv.js";
export {
  createVlmClient,
  DEFAULT_DASHSCOPE_BASE_URL,
  encodeImageBase64,
  MAX_VLM_IMAGE_BYTES,
  VL_MODEL_NAME,
  type VlmCallResult,
  type VlmClient,
  type VlmConfig,
} from "./vlm-client.js";
export {
  extractPdfImages,
  MAX_PDF_IMAGES_PER_FILE,
  type ExtractedPdfImage,
  type PdfImageExtraction,
  type PdfPageRaster,
} from "./pdf-images.js";
export {
  MAX_PDF_PAGES_PER_FILE,
  MAX_PDF_RENDER_PIXELS,
  RENDER_DPI,
  renderPdfPages,
  renderPdfPagesFromBytes,
  type PdfPageRendering,
  type RenderedPdfPage,
  type RenderPdfPagesOptions,
} from "./pdf-pages.js";
export {
  createVlmTools,
  ensureImageInFigures,
  resolveVlmConfig,
  sha256File,
  type EnsureFigureResult,
  type VlmChartMeta,
  type VlmChartSummary,
  type VlmResult,
  type VlmResultError,
  type VlmResultOk,
  type VlmToolHooks,
  type VlmTools,
  type VlmToolsConfig,
} from "./chart-extraction.js";
export {
  extractRegisteredPaperChartEvidence,
  parseRegisteredJatsPaperMeta,
  parseRegisteredPaperChartResponse,
  REGISTERED_PAPER_CHART_CARRIER_KIND,
  REGISTERED_PAPER_CHART_EXTRACTION_IMPLEMENTATION,
  REGISTERED_PAPER_CHART_EXTRACTION_VERSION,
  REGISTERED_PAPER_CHART_PROMPT,
  REGISTERED_PAPER_RENDER_DPI,
  REGISTERED_PAPER_CHART_PROMPT_VERSION,
  type ParsedActivityCandidate,
  type ParsedExperimentCandidate,
  type ParsedPaperMetaCandidate,
  type ParsedPointCandidate,
  type ParsedSeriesCandidate,
  type RegisteredPaperChartCarrierSummary,
  type RegisteredPaperChartEvidenceResult,
  type RegisteredPaperChartExtractionDeps,
  type RegisteredPaperChartExtractionRequest,
  type RegisteredPaperChartResponse,
} from "./registered-paper-chart-extraction.js";
