"""OpenAI-compatible provider model catalog entries."""

from __future__ import annotations

from .schemas import Capabilities, QwenModelEntry

COMPATIBLE_MODELS: dict[str, QwenModelEntry] = {
    "gpt-4o": QwenModelEntry(
        id="gpt-4o",
        name="GPT-4o",
        description="OpenAI 多模态旗舰模型，支持图片、音频输入。",
        context_window=128_000,
        suggested_max_tokens=16_384,
        capabilities=Capabilities(text=True, image=True, video=False, audio=False),
    ),
    "gpt-4o-mini": QwenModelEntry(
        id="gpt-4o-mini",
        name="GPT-4o Mini",
        description="GPT-4o 轻量版，性价比优秀，适合日常任务。",
        context_window=128_000,
        suggested_max_tokens=16_384,
        capabilities=Capabilities(text=True, image=True, video=False, audio=False),
    ),
    "gpt-4-turbo": QwenModelEntry(
        id="gpt-4-turbo",
        name="GPT-4 Turbo",
        description="OpenAI GPT-4 Turbo 模型，支持 128K 上下文。",
        context_window=128_000,
        suggested_max_tokens=4_096,
        capabilities=Capabilities(text=True, image=True, video=False, audio=False),
    ),
    "gpt-4": QwenModelEntry(
        id="gpt-4",
        name="GPT-4",
        description="OpenAI GPT-4 基础模型，稳定可靠（已弃用）。",
        context_window=8_192,
        suggested_max_tokens=4_096,
        capabilities=Capabilities(text=True, image=False, video=False, audio=False),
    ),
    "gpt-4.1": QwenModelEntry(
        id="gpt-4.1",
        name="GPT-4.1",
        description="GPT-4.1 智能非推理模型，1M 上下文。",
        context_window=1_047_576,
        suggested_max_tokens=32_768,
        capabilities=Capabilities(text=True, image=True, video=False, audio=False),
    ),
    "gpt-4.1-mini": QwenModelEntry(
        id="gpt-4.1-mini",
        name="GPT-4.1 Mini",
        description="GPT-4.1 轻量版，更小更快。",
        context_window=1_047_576,
        suggested_max_tokens=32_768,
        capabilities=Capabilities(text=True, image=True, video=False, audio=False),
    ),
    "gpt-4.1-nano": QwenModelEntry(
        id="gpt-4.1-nano",
        name="GPT-4.1 Nano",
        description="GPT-4.1 最快速、最具成本效益的版本。",
        context_window=1_047_576,
        suggested_max_tokens=32_768,
        capabilities=Capabilities(text=True, image=True, video=False, audio=False),
    ),
    "o1": QwenModelEntry(
        id="o1",
        name="o1",
        description="OpenAI o1 推理模型，擅长复杂数学、科学推理（已弃用）。",
        context_window=200_000,
        suggested_max_tokens=32_768,
        capabilities=Capabilities(text=True, image=True, video=False, audio=False),
    ),
    "o3": QwenModelEntry(
        id="o3",
        name="o3",
        description="OpenAI o3 推理模型，用于复杂任务。",
        context_window=200_000,
        suggested_max_tokens=32_768,
        capabilities=Capabilities(text=True, image=True, video=False, audio=False),
    ),
    "o3-mini": QwenModelEntry(
        id="o3-mini",
        name="o3 Mini",
        description="OpenAI o3 轻量推理模型，支持可调推理力度（已弃用）。",
        context_window=200_000,
        suggested_max_tokens=32_768,
        capabilities=Capabilities(text=True, image=True, video=False, audio=False),
    ),
    "o3-pro": QwenModelEntry(
        id="o3-pro",
        name="o3 Pro",
        description="o3 高算力版本，产生更好响应。",
        context_window=200_000,
        suggested_max_tokens=32_768,
        capabilities=Capabilities(text=True, image=True, video=False, audio=False),
    ),
    "o4-mini": QwenModelEntry(
        id="o4-mini",
        name="o4 Mini",
        description="快速、经济的推理模型（已弃用，建议使用 GPT-5 mini）。",
        context_window=200_000,
        suggested_max_tokens=32_768,
        capabilities=Capabilities(text=True, image=True, video=False, audio=False),
    ),
    "gpt-5": QwenModelEntry(
        id="gpt-5",
        name="GPT-5",
        description="GPT-5 智能推理模型，支持可配置推理力度。",
        context_window=400_000,
        suggested_max_tokens=32_768,
        capabilities=Capabilities(text=True, image=True, video=False, audio=False),
    ),
    "gpt-5-mini": QwenModelEntry(
        id="gpt-5-mini",
        name="GPT-5 Mini",
        description="接近前沿智能的经济型模型，低延迟高吞吐。",
        context_window=400_000,
        suggested_max_tokens=32_768,
        capabilities=Capabilities(text=True, image=True, video=False, audio=False),
    ),
    "gpt-5-nano": QwenModelEntry(
        id="gpt-5-nano",
        name="GPT-5 Nano",
        description="最快、最具成本效益的 GPT-5 版本。",
        context_window=400_000,
        suggested_max_tokens=32_768,
        capabilities=Capabilities(text=True, image=True, video=False, audio=False),
    ),
    "gpt-5-pro": QwenModelEntry(
        id="gpt-5-pro",
        name="GPT-5 Pro",
        description="GPT-5 高算力版本，产生更精准的响应。",
        context_window=400_000,
        suggested_max_tokens=32_768,
        capabilities=Capabilities(text=True, image=True, video=False, audio=False),
    ),
    "gpt-5.1": QwenModelEntry(
        id="gpt-5.1",
        name="GPT-5.1",
        description="GPT-5.1 编码与智能体任务最佳模型，支持可配置推理力度。",
        context_window=400_000,
        suggested_max_tokens=32_768,
        capabilities=Capabilities(text=True, image=True, video=False, audio=False),
    ),
    "gpt-5.2": QwenModelEntry(
        id="gpt-5.2",
        name="GPT-5.2",
        description="上一代旗舰模型，支持可配置推理力度。",
        context_window=400_000,
        suggested_max_tokens=32_768,
        capabilities=Capabilities(text=True, image=True, video=False, audio=False),
    ),
    "gpt-5.2-pro": QwenModelEntry(
        id="gpt-5.2-pro",
        name="GPT-5.2 Pro",
        description="GPT-5.2 高算力版本，产生更精准的响应。",
        context_window=400_000,
        suggested_max_tokens=32_768,
        capabilities=Capabilities(text=True, image=True, video=False, audio=False),
    ),
    "gpt-5.3-codex": QwenModelEntry(
        id="gpt-5.3-codex",
        name="GPT-5.3 Codex",
        description="最强大的智能体编码模型。",
        context_window=400_000,
        suggested_max_tokens=32_768,
        capabilities=Capabilities(text=True, image=True, video=False, audio=False),
    ),
    "gpt-5.4": QwenModelEntry(
        id="gpt-5.4",
        name="GPT-5.4",
        description="面向编码与专业工作的平价模型。",
        context_window=1_050_000,
        suggested_max_tokens=32_768,
        capabilities=Capabilities(text=True, image=True, video=False, audio=False),
    ),
    "gpt-5.4-pro": QwenModelEntry(
        id="gpt-5.4-pro",
        name="GPT-5.4 Pro",
        description="GPT-5.4 高算力版本，产生更精准的响应。",
        context_window=1_050_000,
        suggested_max_tokens=32_768,
        capabilities=Capabilities(text=True, image=True, video=False, audio=False),
    ),
    "gpt-5.4-mini": QwenModelEntry(
        id="gpt-5.4-mini",
        name="GPT-5.4 Mini",
        description="最强的 mini 模型，适合编码、Computer Use 与子代理。",
        context_window=400_000,
        suggested_max_tokens=32_768,
        capabilities=Capabilities(text=True, image=True, video=False, audio=False),
    ),
    "gpt-5.4-nano": QwenModelEntry(
        id="gpt-5.4-nano",
        name="GPT-5.4 Nano",
        description="最便宜的 GPT-5.4 级模型，适合高吞吐简单任务。",
        context_window=400_000,
        suggested_max_tokens=32_768,
        capabilities=Capabilities(text=True, image=True, video=False, audio=False),
    ),
    "gpt-5.5": QwenModelEntry(
        id="gpt-5.5",
        name="GPT-5.5",
        description="GPT-5.5 前沿模型，适用于最复杂的专业工作。",
        context_window=1_050_000,
        suggested_max_tokens=32_768,
        capabilities=Capabilities(text=True, image=True, video=False, audio=False),
    ),
    "gpt-5.5-pro": QwenModelEntry(
        id="gpt-5.5-pro",
        name="GPT-5.5 Pro",
        description="GPT-5.5 高算力版本，产生更精准的响应。",
        context_window=1_050_000,
        suggested_max_tokens=32_768,
        capabilities=Capabilities(text=True, image=True, video=False, audio=False),
    ),
    "gpt-5.6": QwenModelEntry(
        id="gpt-5.6",
        name="GPT-5.6",
        description="GPT-5.6 旗舰模型别名（指向 GPT-5.6 Sol）。",
        context_window=1_050_000,
        suggested_max_tokens=32_768,
        capabilities=Capabilities(text=True, image=True, video=False, audio=False),
    ),
    "gpt-5.6-luna": QwenModelEntry(
        id="gpt-5.6-luna",
        name="GPT-5.6 Luna",
        description="GPT-5.6 经济型模型，面向高吞吐成本敏感场景。",
        context_window=1_050_000,
        suggested_max_tokens=32_768,
        capabilities=Capabilities(text=True, image=True, video=False, audio=False),
    ),
    "gpt-5.6-terra": QwenModelEntry(
        id="gpt-5.6-terra",
        name="GPT-5.6 Terra",
        description="GPT-5.6 平衡智能与成本的模型。",
        context_window=1_050_000,
        suggested_max_tokens=32_768,
        capabilities=Capabilities(text=True, image=True, video=False, audio=False),
    ),
    "gpt-5.6-sol": QwenModelEntry(
        id="gpt-5.6-sol",
        name="GPT-5.6 Sol",
        description="GPT-5.6 旗舰模型，适用于复杂推理与编码。",
        context_window=1_050_000,
        suggested_max_tokens=32_768,
        capabilities=Capabilities(text=True, image=True, video=False, audio=False),
        recommended=True,
    ),
    "deepseek-v4-flash": QwenModelEntry(
        id="deepseek-v4-flash",
        name="DeepSeek V4 Flash",
        description="DeepSeek V4 Flash 高速对话模型，1M 上下文，支持思考与非思考模式。",
        context_window=1_000_000,
        suggested_max_tokens=32_768,
        capabilities=Capabilities(text=True, image=False, video=False, audio=False),
        recommended=True,
    ),
    "deepseek-v4-pro": QwenModelEntry(
        id="deepseek-v4-pro",
        name="DeepSeek V4 Pro",
        description="DeepSeek V4 Pro 旗舰模型，1M 上下文，更强推理能力。",
        context_window=1_000_000,
        suggested_max_tokens=32_768,
        capabilities=Capabilities(text=True, image=False, video=False, audio=False),
    ),
    "deepseek-chat": QwenModelEntry(
        id="deepseek-chat",
        name="DeepSeek Chat",
        description="DeepSeek 对话模型别名（已于 2026-07-24 弃用，路由至 V4 Flash）。",
        context_window=128_000,
        suggested_max_tokens=8_192,
        capabilities=Capabilities(text=True, image=False, video=False, audio=False),
    ),
    "deepseek-reasoner": QwenModelEntry(
        id="deepseek-reasoner",
        name="DeepSeek Reasoner",
        description="DeepSeek 推理模型别名（已于 2026-07-24 弃用，路由至 V4 Flash 思考模式）。",
        context_window=128_000,
        suggested_max_tokens=32_768,
        capabilities=Capabilities(text=True, image=False, video=False, audio=False),
    ),
    "deepseek-v3": QwenModelEntry(
        id="deepseek-v3",
        name="DeepSeek V3",
        description="DeepSeek V3 开源模型（中转站常用 ID）。",
        context_window=164_000,
        suggested_max_tokens=8_192,
        capabilities=Capabilities(text=True, image=False, video=False, audio=False),
    ),
    "deepseek-r1": QwenModelEntry(
        id="deepseek-r1",
        name="DeepSeek R1",
        description="DeepSeek R1 开源推理模型（中转站常用 ID）。",
        context_window=164_000,
        suggested_max_tokens=8_192,
        capabilities=Capabilities(text=True, image=False, video=False, audio=False),
    ),
    "moonshot-v1-8k": QwenModelEntry(
        id="moonshot-v1-8k",
        name="Moonshot V1 8K",
        description="月之暗面 Kimi 模型，8K 上下文版本。",
        context_window=8_192,
        suggested_max_tokens=4_096,
        capabilities=Capabilities(text=True, image=False, video=False, audio=False),
    ),
    "moonshot-v1-32k": QwenModelEntry(
        id="moonshot-v1-32k",
        name="Moonshot V1 32K",
        description="月之暗面 Kimi 模型，32K 上下文版本。",
        context_window=32_768,
        suggested_max_tokens=8_192,
        capabilities=Capabilities(text=True, image=False, video=False, audio=False),
    ),
    "moonshot-v1-128k": QwenModelEntry(
        id="moonshot-v1-128k",
        name="Moonshot V1 128K",
        description="月之暗面 Kimi 模型，128K 上下文版本，适合长文档分析。",
        context_window=131_072,
        suggested_max_tokens=8_192,
        capabilities=Capabilities(text=True, image=False, video=False, audio=False),
    ),
    "kimi-k3": QwenModelEntry(
        id="kimi-k3",
        name="Kimi K3",
        description="Kimi 旗舰模型，1M 上下文，原生支持视觉理解，面向软件工程与深度推理。",
        context_window=1_048_576,
        suggested_max_tokens=32_768,
        capabilities=Capabilities(text=True, image=True, video=True, audio=False),
        recommended=True,
    ),
    "kimi-k2.7-code": QwenModelEntry(
        id="kimi-k2.7-code",
        name="Kimi K2.7 Code",
        description="Kimi 编程模型，256K 上下文，长上下文指令遵循更可靠。",
        context_window=262_144,
        suggested_max_tokens=32_768,
        capabilities=Capabilities(text=True, image=True, video=True, audio=False),
    ),
    "kimi-k2.7-code-highspeed": QwenModelEntry(
        id="kimi-k2.7-code-highspeed",
        name="Kimi K2.7 Code HighSpeed",
        description="Kimi K2.7 Code 高速版，输出约 180 Tokens/s。",
        context_window=262_144,
        suggested_max_tokens=32_768,
        capabilities=Capabilities(text=True, image=True, video=True, audio=False),
    ),
    "kimi-k2.6": QwenModelEntry(
        id="kimi-k2.6",
        name="Kimi K2.6",
        description="Kimi 通用模型，256K 上下文，支持思考与非思考模式。",
        context_window=262_144,
        suggested_max_tokens=32_768,
        capabilities=Capabilities(text=True, image=True, video=True, audio=False),
    ),
    "kimi-k2.5": QwenModelEntry(
        id="kimi-k2.5",
        name="Kimi K2.5",
        description="Kimi 多模态模型，256K 上下文（2026-08-31 起停止服务）。",
        context_window=262_144,
        suggested_max_tokens=32_768,
        capabilities=Capabilities(text=True, image=True, video=True, audio=False),
    ),
    "glm-4-plus": QwenModelEntry(
        id="glm-4-plus",
        name="GLM-4 Plus",
        description="智谱 AI GLM-4 旗舰模型，支持 128K 上下文。",
        context_window=128_000,
        suggested_max_tokens=8_192,
        capabilities=Capabilities(text=True, image=False, video=False, audio=False),
    ),
    "glm-4-flash": QwenModelEntry(
        id="glm-4-flash",
        name="GLM-4 Flash",
        description="智谱 AI GLM-4 轻量快速模型。",
        context_window=128_000,
        suggested_max_tokens=4_096,
        capabilities=Capabilities(text=True, image=False, video=False, audio=False),
    ),
    "glm-4v-plus": QwenModelEntry(
        id="glm-4v-plus",
        name="GLM-4V Plus",
        description="智谱 AI GLM-4V 多模态模型，支持图片理解。",
        context_window=128_000,
        suggested_max_tokens=4_096,
        capabilities=Capabilities(text=True, image=True, video=False, audio=False),
    ),
    "glm-4-long": QwenModelEntry(
        id="glm-4-long",
        name="GLM-4 Long",
        description="智谱 AI GLM-4-Long 超长文本模型，支持 1M 上下文。",
        context_window=1_000_000,
        suggested_max_tokens=4_096,
        capabilities=Capabilities(text=True, image=False, video=False, audio=False),
    ),
    "glm-4-flash-250414": QwenModelEntry(
        id="glm-4-flash-250414",
        name="GLM-4 Flash 250414",
        description="智谱 AI GLM-4-Flash-250414 免费模型。",
        context_window=128_000,
        suggested_max_tokens=32_768,
        capabilities=Capabilities(text=True, image=False, video=False, audio=False),
    ),
    "glm-4.5": QwenModelEntry(
        id="glm-4.5",
        name="GLM-4.5",
        description="智谱 AI GLM-4.5 模型，128K 上下文，支持思考模式与工具调用。",
        context_window=131_072,
        suggested_max_tokens=65_536,
        capabilities=Capabilities(text=True, image=False, video=False, audio=False),
        recommended=True,
    ),
    "glm-4.5-air": QwenModelEntry(
        id="glm-4.5-air",
        name="GLM-4.5 Air",
        description="智谱 AI GLM-4.5-Air 轻量版，兼顾性能与成本。",
        context_window=131_072,
        suggested_max_tokens=65_536,
        capabilities=Capabilities(text=True, image=False, video=False, audio=False),
    ),
    "glm-4.5-flash": QwenModelEntry(
        id="glm-4.5-flash",
        name="GLM-4.5 Flash",
        description="智谱 AI GLM-4.5-Flash 免费模型。",
        context_window=131_072,
        suggested_max_tokens=65_536,
        capabilities=Capabilities(text=True, image=False, video=False, audio=False),
    ),
    "glm-4.5v": QwenModelEntry(
        id="glm-4.5v",
        name="GLM-4.5V",
        description="智谱 AI GLM-4.5V 视觉推理模型。",
        context_window=64_000,
        suggested_max_tokens=16_384,
        capabilities=Capabilities(text=True, image=True, video=False, audio=False),
    ),
    "glm-4.6": QwenModelEntry(
        id="glm-4.6",
        name="GLM-4.6",
        description="智谱 AI GLM-4.6 高级编码、复杂推理与工具调用模型，200K 上下文。",
        context_window=204_800,
        suggested_max_tokens=65_536,
        capabilities=Capabilities(text=True, image=False, video=False, audio=False),
    ),
    "glm-4.6v": QwenModelEntry(
        id="glm-4.6v",
        name="GLM-4.6V",
        description="智谱 AI GLM-4.6V 视觉推理模型，原生支持工具调用与长上下文。",
        context_window=128_000,
        suggested_max_tokens=32_768,
        capabilities=Capabilities(text=True, image=True, video=False, audio=False),
    ),
    "glm-4.7": QwenModelEntry(
        id="glm-4.7",
        name="GLM-4.7",
        description="智谱 AI GLM-4.7 通用对话、推理与智能体能力全面升级，200K 上下文。",
        context_window=204_800,
        suggested_max_tokens=65_536,
        capabilities=Capabilities(text=True, image=False, video=False, audio=False),
    ),
    "glm-4.7-flash": QwenModelEntry(
        id="glm-4.7-flash",
        name="GLM-4.7 Flash",
        description="智谱 AI GLM-4.7-Flash 免费轻量模型，200K 上下文。",
        context_window=200_000,
        suggested_max_tokens=65_536,
        capabilities=Capabilities(text=True, image=False, video=False, audio=False),
    ),
    "glm-4.7-flashx": QwenModelEntry(
        id="glm-4.7-flashx",
        name="GLM-4.7 FlashX",
        description="智谱 AI GLM-4.7-FlashX 高速低价模型，200K 上下文。",
        context_window=200_000,
        suggested_max_tokens=65_536,
        capabilities=Capabilities(text=True, image=False, video=False, audio=False),
    ),
    "glm-5": QwenModelEntry(
        id="glm-5",
        name="GLM-5",
        description="智谱 AI GLM-5 旗舰模型，200K 上下文，擅长 Agentic 长程规划与执行。",
        context_window=204_800,
        suggested_max_tokens=65_536,
        capabilities=Capabilities(text=True, image=False, video=False, audio=False),
    ),
    "glm-5-turbo": QwenModelEntry(
        id="glm-5-turbo",
        name="GLM-5 Turbo",
        description="智谱 AI GLM-5-Turbo 高速版，200K 上下文。",
        context_window=200_000,
        suggested_max_tokens=65_536,
        capabilities=Capabilities(text=True, image=False, video=False, audio=False),
    ),
    "glm-5.1": QwenModelEntry(
        id="glm-5.1",
        name="GLM-5.1",
        description="智谱 AI GLM-5.1 高性能模型，200K 上下文，擅长复杂代码与长程任务。",
        context_window=200_000,
        suggested_max_tokens=65_536,
        capabilities=Capabilities(text=True, image=False, video=False, audio=False),
    ),
    "glm-5.2": QwenModelEntry(
        id="glm-5.2",
        name="GLM-5.2",
        description="智谱 AI GLM-5.2 旗舰模型，1M 上下文，专为长程任务设计。",
        context_window=1_000_000,
        suggested_max_tokens=65_536,
        capabilities=Capabilities(text=True, image=False, video=False, audio=False),
        recommended=True,
    ),
    "glm-5v-turbo": QwenModelEntry(
        id="glm-5v-turbo",
        name="GLM-5V Turbo",
        description="智谱 AI GLM-5V-Turbo 多模态 Agent 基座模型，支持图像、视频、文本输入。",
        context_window=200_000,
        suggested_max_tokens=65_536,
        capabilities=Capabilities(text=True, image=True, video=True, audio=False),
    ),
    "glm-4.6v-flash": QwenModelEntry(
        id="glm-4.6v-flash",
        name="GLM-4.6V Flash",
        description="智谱 AI GLM-4.6V-Flash 免费视觉模型，128K 上下文。",
        context_window=128_000,
        suggested_max_tokens=16_384,
        capabilities=Capabilities(text=True, image=True, video=False, audio=False),
    ),
    "glm-4.6v-flashx": QwenModelEntry(
        id="glm-4.6v-flashx",
        name="GLM-4.6V FlashX",
        description="智谱 AI GLM-4.6V-FlashX 轻量高速视觉模型，128K 上下文。",
        context_window=128_000,
        suggested_max_tokens=16_384,
        capabilities=Capabilities(text=True, image=True, video=False, audio=False),
    ),
    "glm-4v-flash": QwenModelEntry(
        id="glm-4v-flash",
        name="GLM-4V Flash",
        description="智谱 AI GLM-4V-Flash 免费模型，支持基础图像理解。",
        context_window=16_000,
        suggested_max_tokens=1_024,
        capabilities=Capabilities(text=True, image=True, video=False, audio=False),
    ),
    "baichuan4": QwenModelEntry(
        id="baichuan4",
        name="Baichuan4",
        description="百川智能旗舰模型，支持 32K 上下文。",
        context_window=32_768,
        suggested_max_tokens=4_096,
        capabilities=Capabilities(text=True, image=False, video=False, audio=False),
    ),
    "baichuan4-turbo": QwenModelEntry(
        id="baichuan4-turbo",
        name="Baichuan4 Turbo",
        description="百川智能 Baichuan4-Turbo 模型，32K 上下文。",
        context_window=32_768,
        suggested_max_tokens=4_096,
        capabilities=Capabilities(text=True, image=False, video=False, audio=False),
    ),
    "baichuan4-air": QwenModelEntry(
        id="baichuan4-air",
        name="Baichuan4 Air",
        description="百川智能 Baichuan4-Air 经济型模型，32K 上下文。",
        context_window=32_768,
        suggested_max_tokens=4_096,
        capabilities=Capabilities(text=True, image=False, video=False, audio=False),
    ),
    "baichuan3-turbo": QwenModelEntry(
        id="baichuan3-turbo",
        name="Baichuan3 Turbo",
        description="百川智能轻量快速模型，适合日常对话。",
        context_window=32_768,
        suggested_max_tokens=4_096,
        capabilities=Capabilities(text=True, image=False, video=False, audio=False),
    ),
    "baichuan3-turbo-128k": QwenModelEntry(
        id="baichuan3-turbo-128k",
        name="Baichuan3 Turbo 128K",
        description="百川智能 Baichuan3-Turbo 长上下文版本，128K。",
        context_window=131_072,
        suggested_max_tokens=4_096,
        capabilities=Capabilities(text=True, image=False, video=False, audio=False),
    ),
    "baichuan-m3-plus": QwenModelEntry(
        id="baichuan-m3-plus",
        name="Baichuan M3 Plus",
        description="百川智能当前主力模型，32K 上下文，自动触发医疗搜索。",
        context_window=32_768,
        suggested_max_tokens=4_096,
        capabilities=Capabilities(text=True, image=False, video=False, audio=False),
        recommended=True,
    ),
    "baichuan-m3": QwenModelEntry(
        id="baichuan-m3",
        name="Baichuan M3",
        description="百川智能 Baichuan-M3 模型，32K 上下文。",
        context_window=32_768,
        suggested_max_tokens=4_096,
        capabilities=Capabilities(text=True, image=False, video=False, audio=False),
    ),
    "meta-llama/llama-4-scout-17b-16e-instruct": QwenModelEntry(
        id="meta-llama/llama-4-scout-17b-16e-instruct",
        name="Llama 4 Scout",
        description="Groq 托管的 Meta Llama 4 Scout 17B 模型，128K 上下文，支持视觉与工具调用。",
        context_window=131_072,
        suggested_max_tokens=8_192,
        capabilities=Capabilities(text=True, image=True, video=False, audio=False),
    ),
    "llama-3.3-70b-versatile": QwenModelEntry(
        id="llama-3.3-70b-versatile",
        name="Llama 3.3 70B",
        description="Groq 托管的 Meta Llama 3.3 70B 模型，131K 上下文。",
        context_window=131_072,
        suggested_max_tokens=32_768,
        capabilities=Capabilities(text=True, image=False, video=False, audio=False),
        recommended=True,
    ),
    "llama-3.1-8b-instant": QwenModelEntry(
        id="llama-3.1-8b-instant",
        name="Llama 3.1 8B",
        description="Groq 托管的 Meta Llama 3.1 8B 模型，131K 上下文。",
        context_window=131_072,
        suggested_max_tokens=32_768,
        capabilities=Capabilities(text=True, image=False, video=False, audio=False),
    ),
    "openai/gpt-oss-120b": QwenModelEntry(
        id="openai/gpt-oss-120b",
        name="GPT OSS 120B",
        description="OpenAI 开源 GPT-OSS 120B 模型，支持推理与工具调用。",
        context_window=131_072,
        suggested_max_tokens=32_768,
        capabilities=Capabilities(text=True, image=False, video=False, audio=False),
    ),
    "openai/gpt-oss-20b": QwenModelEntry(
        id="openai/gpt-oss-20b",
        name="GPT OSS 20B",
        description="OpenAI 开源 GPT-OSS 20B 模型。",
        context_window=131_072,
        suggested_max_tokens=32_768,
        capabilities=Capabilities(text=True, image=False, video=False, audio=False),
    ),
    "qwen/qwen3.6-27b": QwenModelEntry(
        id="qwen/qwen3.6-27b",
        name="Qwen3.6 27B",
        description="Groq 托管的 Qwen3.6-27B 模型，131K 上下文。",
        context_window=131_072,
        suggested_max_tokens=16_384,
        capabilities=Capabilities(text=True, image=False, video=False, audio=False),
    ),
    "grok-4.5": QwenModelEntry(
        id="grok-4.5",
        name="Grok 4.5",
        description="xAI Grok 4.5 旗舰模型，500K 上下文，可配置推理力度，支持图像输入。",
        context_window=500_000,
        suggested_max_tokens=32_768,
        capabilities=Capabilities(text=True, image=True, video=False, audio=False),
        recommended=True,
    ),
    "grok-4.3": QwenModelEntry(
        id="grok-4.3",
        name="Grok 4.3",
        description="xAI Grok 4.3 模型，1M 上下文，支持视觉输入与工具调用。",
        context_window=1_000_000,
        suggested_max_tokens=16_384,
        capabilities=Capabilities(text=True, image=True, video=False, audio=False),
    ),
    "mistral-large-latest": QwenModelEntry(
        id="mistral-large-latest",
        name="Mistral Large",
        description="Mistral Large 3 旗舰模型，262K 上下文，开源多模态。",
        context_window=262_144,
        suggested_max_tokens=32_768,
        capabilities=Capabilities(text=True, image=True, video=False, audio=False),
        recommended=True,
    ),
    "mistral-medium-latest": QwenModelEntry(
        id="mistral-medium-latest",
        name="Mistral Medium",
        description="Mistral Medium 3.5 前沿多模态模型，262K 上下文。",
        context_window=262_144,
        suggested_max_tokens=32_768,
        capabilities=Capabilities(text=True, image=True, video=False, audio=False),
    ),
    "mistral-small-latest": QwenModelEntry(
        id="mistral-small-latest",
        name="Mistral Small",
        description="Mistral Small 4 混合模型，256K 上下文，统一指令、推理与编码。",
        context_window=256_000,
        suggested_max_tokens=32_768,
        capabilities=Capabilities(text=True, image=True, video=False, audio=False),
    ),
    "MiniMax-M3": QwenModelEntry(
        id="MiniMax-M3",
        name="MiniMax M3",
        description="MiniMax M3 原生多模态模型，1M 上下文，面向 Agent 推理、工具调用与编码。",
        context_window=1_000_000,
        suggested_max_tokens=32_768,
        capabilities=Capabilities(text=True, image=True, video=True, audio=False),
        recommended=True,
    ),
    "MiniMax-M2.7": QwenModelEntry(
        id="MiniMax-M2.7",
        name="MiniMax M2.7",
        description="MiniMax M2.7 语言模型，205K 上下文。",
        context_window=204_800,
        suggested_max_tokens=32_768,
        capabilities=Capabilities(text=True, image=False, video=False, audio=False),
    ),
    "MiniMax/speech-2.8-hd": QwenModelEntry(
        id="MiniMax/speech-2.8-hd",
        name="MiniMax Speech 2.8 HD",
        description="MiniMax 语音合成模型（DashScope 三方直供）。",
        context_window=1,
        suggested_max_tokens=1,
        capabilities=Capabilities(text=True, image=False, video=False, audio=True),
    ),
    "happyhorse-1.0-video-edit": QwenModelEntry(
        id="happyhorse-1.0-video-edit",
        name="HappyHorse 1.0 Video Edit",
        description="快手可灵 AI 视频编辑模型。",
        context_window=1,
        suggested_max_tokens=1,
        capabilities=Capabilities(text=True, image=False, video=True, audio=False),
    ),
    "happyhorse-1.1-i2v": QwenModelEntry(
        id="happyhorse-1.1-i2v",
        name="HappyHorse 1.1 I2V",
        description="快手可灵 1.1 图生视频模型。",
        context_window=1,
        suggested_max_tokens=1,
        capabilities=Capabilities(text=True, image=True, video=True, audio=False),
    ),
    "happyhorse-1.1-r2v": QwenModelEntry(
        id="happyhorse-1.1-r2v",
        name="HappyHorse 1.1 R2V",
        description="快手可灵 1.1 参考视频生成模型。",
        context_window=1,
        suggested_max_tokens=1,
        capabilities=Capabilities(text=True, image=False, video=True, audio=False),
    ),
    "happyhorse-1.1-t2v": QwenModelEntry(
        id="happyhorse-1.1-t2v",
        name="HappyHorse 1.1 T2V",
        description="快手可灵 1.1 文生视频模型。",
        context_window=1,
        suggested_max_tokens=1,
        capabilities=Capabilities(text=True, image=False, video=True, audio=False),
    ),
    "mimo-v2.5-pro": QwenModelEntry(
        id="mimo-v2.5-pro",
        name="Xiaomi MiMo 2.5 Pro",
        description="小米 MiMo 2.5 Pro 视频生成模型（DashScope 三方直供）。",
        context_window=1,
        suggested_max_tokens=1,
        capabilities=Capabilities(text=True, image=False, video=True, audio=False),
    ),
    "Tripo/Tripo-H3.1": QwenModelEntry(
        id="Tripo/Tripo-H3.1",
        name="Tripo H3.1",
        description="Tripo 3D 生成模型 H3.1（DashScope 三方直供）。",
        context_window=1,
        suggested_max_tokens=1,
        capabilities=Capabilities(text=True, image=False, video=False, audio=False),
    ),
    "Tripo/Tripo-P1.0": QwenModelEntry(
        id="Tripo/Tripo-P1.0",
        name="Tripo P1.0",
        description="Tripo 3D 生成模型 P1.0（DashScope 三方直供）。",
        context_window=1,
        suggested_max_tokens=1,
        capabilities=Capabilities(text=True, image=False, video=False, audio=False),
    ),
}
