"""Built-in Qwen-family model catalog entries."""

from __future__ import annotations

from .schemas import Capabilities, QwenModelEntry

# allow: SIZE_OK — pure-data-table (model entry dict)
QWEN_MODELS: dict[str, QwenModelEntry] = {
    "qwen-plus": QwenModelEntry(
        id="qwen-plus",
        name="Qwen Plus",
        description="Qwen 主力文本模型，平衡性能与成本，适合日常研究对话。",
        context_window=131_072,
        suggested_max_tokens=8_192,
        capabilities=Capabilities(text=True),
        recommended=True,
    ),
    "qwen-max": QwenModelEntry(
        id="qwen-max",
        name="Qwen Max",
        description="Qwen 最强文本模型，适合复杂推理、深度分析和长文档理解。",
        context_window=32_768,
        suggested_max_tokens=8_192,
        capabilities=Capabilities(text=True),
    ),
    "qwen-turbo": QwenModelEntry(
        id="qwen-turbo",
        name="Qwen Turbo",
        description="轻量快速模型，适合简单问答、摘要、分类等低延迟场景。",
        context_window=1_000_000,
        suggested_max_tokens=4_096,
        capabilities=Capabilities(text=True),
    ),
    "qwen-vl-max": QwenModelEntry(
        id="qwen-vl-max",
        name="Qwen VL Max",
        description="最强视觉语言模型，支持图像理解、图表提取、OCR。",
        context_window=32_768,
        suggested_max_tokens=4_096,
        capabilities=Capabilities(text=True, image=True),
    ),
    "qwen-vl-plus": QwenModelEntry(
        id="qwen-vl-plus",
        name="Qwen VL Plus",
        description="视觉语言模型，支持图文理解，性价比高。",
        context_window=32_768,
        suggested_max_tokens=4_096,
        capabilities=Capabilities(text=True, image=True),
    ),
    "qwen2.5-vl-72b-instruct": QwenModelEntry(
        id="qwen2.5-vl-72b-instruct",
        name="Qwen2.5 VL 72B",
        description="Qwen2.5 系列 72B 视觉语言模型，支持图像与视频理解。",
        context_window=32_768,
        suggested_max_tokens=4_096,
        capabilities=Capabilities(text=True, image=True, video=True),
    ),
    "qwen2.5-vl-32b-instruct": QwenModelEntry(
        id="qwen2.5-vl-32b-instruct",
        name="Qwen2.5 VL 32B",
        description="Qwen2.5 系列 32B 视觉语言模型，支持图像与视频理解。",
        context_window=32_768,
        suggested_max_tokens=4_096,
        capabilities=Capabilities(text=True, image=True, video=True),
    ),
    "qwen-vl-ocr": QwenModelEntry(
        id="qwen-vl-ocr",
        name="Qwen VL OCR",
        description="专注于 OCR 识别和文档数字化的视觉模型。",
        context_window=32_768,
        suggested_max_tokens=4_096,
        capabilities=Capabilities(text=True, image=True),
    ),
    "qwen2-audio": QwenModelEntry(
        id="qwen2-audio",
        name="Qwen2 Audio",
        description="语音理解模型，支持语音识别、语音对话与音频分析。",
        context_window=32_768,
        suggested_max_tokens=4_096,
        capabilities=Capabilities(text=True, audio=True),
    ),
    "qwen-omni-turbo": QwenModelEntry(
        id="qwen-omni-turbo",
        name="Qwen Omni Turbo",
        description="全模态模型（文本+图像+视频+音频），适合多模态交互场景。",
        context_window=32_768,
        suggested_max_tokens=4_096,
        capabilities=Capabilities(text=True, image=True, video=True, audio=True),
    ),
    "qwq-32b": QwenModelEntry(
        id="qwq-32b",
        name="QWQ 32B",
        description="推理增强模型（类 o1），擅长数学、逻辑和多步推理。",
        context_window=32_768,
        suggested_max_tokens=8_192,
        capabilities=Capabilities(text=True),
    ),
    "qwq-plus": QwenModelEntry(
        id="qwq-plus",
        name="QWQ Plus",
        description="新一代推理模型，更强的思维链与复杂推理能力。",
        context_window=131_072,
        suggested_max_tokens=16_384,
        capabilities=Capabilities(text=True),
    ),
    "qwen3-235b-a22b": QwenModelEntry(
        id="qwen3-235b-a22b",
        name="Qwen3 235B",
        description="Qwen3 系列 MoE 旗舰模型，235B 总参数/22B 激活",
        context_window=32_768,
        suggested_max_tokens=8_192,
        capabilities=Capabilities(text=True, image=True),
    ),
    "qwen3.5-plus": QwenModelEntry(
        id="qwen3.5-plus",
        name="Qwen3.5 Plus",
        description="Qwen3.5 系列视觉语言旗舰模型，1M 超长上下文，支持图像与视频理解。",
        context_window=1_000_000,
        suggested_max_tokens=64_000,
        capabilities=Capabilities(text=True, image=True, video=True),
    ),
    "qwen3.5-plus-2026-04-20": QwenModelEntry(
        id="qwen3.5-plus-2026-04-20",
        name="Qwen3.5 Plus 2026-04-20",
        description="Qwen3.5 Plus 快照版本，1M 超长上下文，支持图像与视频理解。",
        context_window=1_000_000,
        suggested_max_tokens=64_000,
        capabilities=Capabilities(text=True, image=True, video=True),
    ),
    "qwen3.5-plus-2026-02-15": QwenModelEntry(
        id="qwen3.5-plus-2026-02-15",
        name="Qwen3.5 Plus 2026-02-15",
        description="Qwen3.5 Plus 快照版本，1M 超长上下文，支持图像与视频理解。",
        context_window=1_000_000,
        suggested_max_tokens=64_000,
        capabilities=Capabilities(text=True, image=True, video=True),
    ),
    "qwen3.5-flash": QwenModelEntry(
        id="qwen3.5-flash",
        name="Qwen3.5 Flash",
        description="Qwen3.5 系列高速视觉语言模型，1M 超长上下文，支持图像与视频理解。",
        context_window=1_000_000,
        suggested_max_tokens=64_000,
        capabilities=Capabilities(text=True, image=True, video=True),
    ),
    "qwen3.5-flash-2026-02-23": QwenModelEntry(
        id="qwen3.5-flash-2026-02-23",
        name="Qwen3.5 Flash 2026-02-23",
        description="Qwen3.5 Flash 快照版本，1M 超长上下文，支持图像与视频理解。",
        context_window=1_000_000,
        suggested_max_tokens=64_000,
        capabilities=Capabilities(text=True, image=True, video=True),
    ),
    "qwen3.5-397b-a17b": QwenModelEntry(
        id="qwen3.5-397b-a17b",
        name="Qwen3.5 397B A17B",
        description="Qwen3.5 系列 MoE 视觉语言旗舰模型，397B 总参数/17B 激活，支持图像与视频理解。",
        context_window=262_144,
        suggested_max_tokens=64_000,
        capabilities=Capabilities(text=True, image=True, video=True),
    ),
    "qwen3.5-122b-a10b": QwenModelEntry(
        id="qwen3.5-122b-a10b",
        name="Qwen3.5 122B A10B",
        description="Qwen3.5 系列 MoE 视觉语言模型，122B 总参数/10B 激活，支持图像与视频理解。",
        context_window=262_144,
        suggested_max_tokens=64_000,
        capabilities=Capabilities(text=True, image=True, video=True),
    ),
    "qwen3.5-27b": QwenModelEntry(
        id="qwen3.5-27b",
        name="Qwen3.5 27B",
        description="Qwen3.5 系列 27B 密集视觉语言模型，支持图像与视频理解。",
        context_window=262_144,
        suggested_max_tokens=64_000,
        capabilities=Capabilities(text=True, image=True, video=True),
    ),
    "qwen3.5-35b-a3b": QwenModelEntry(
        id="qwen3.5-35b-a3b",
        name="Qwen3.5 35B A3B",
        description="Qwen3.5 系列 MoE 轻量视觉语言模型，高效推理，支持图像与视频理解。",
        context_window=262_144,
        suggested_max_tokens=64_000,
        capabilities=Capabilities(text=True, image=True, video=True),
    ),
    "qwen3.6-35b-a3b": QwenModelEntry(
        id="qwen3.6-35b-a3b",
        name="Qwen3.6 35B A3B",
        description="Qwen3.6 系列 MoE 视觉语言模型，高效推理，支持图像与视频理解。",
        context_window=262_144,
        suggested_max_tokens=64_000,
        capabilities=Capabilities(text=True, image=True, video=True),
    ),
    "qwen3.6-flash": QwenModelEntry(
        id="qwen3.6-flash",
        name="Qwen3.6 Flash",
        description="Qwen3.6 系列高速视觉语言模型，1M 超长上下文，支持图像与视频理解。",
        context_window=1_000_000,
        suggested_max_tokens=64_000,
        capabilities=Capabilities(text=True, image=True, video=True),
    ),
    "qwen3.6-flash-2026-04-16": QwenModelEntry(
        id="qwen3.6-flash-2026-04-16",
        name="Qwen3.6 Flash 2026-04-16",
        description="Qwen3.6 Flash 快照版本，1M 超长上下文，支持图像与视频理解。",
        context_window=1_000_000,
        suggested_max_tokens=64_000,
        capabilities=Capabilities(text=True, image=True, video=True),
    ),
    "qwen3.6-plus": QwenModelEntry(
        id="qwen3.6-plus",
        name="Qwen3.6 Plus",
        description="Qwen3.6 系列视觉语言模型，1M 超长上下文，支持图像与视频理解。",
        context_window=1_000_000,
        suggested_max_tokens=64_000,
        capabilities=Capabilities(text=True, image=True, video=True),
    ),
    "qwen3.6-plus-2026-04-02": QwenModelEntry(
        id="qwen3.6-plus-2026-04-02",
        name="Qwen3.6 Plus 2026-04-02",
        description="Qwen3.6 Plus 快照版本，1M 超长上下文，支持图像与视频理解。",
        context_window=1_000_000,
        suggested_max_tokens=64_000,
        capabilities=Capabilities(text=True, image=True, video=True),
    ),
    "qwen3.7-plus": QwenModelEntry(
        id="qwen3.7-plus",
        name="Qwen3.7 Plus",
        description="Qwen3.7 系列视觉语言模型，1M 超长上下文，支持图像与视频理解。",
        context_window=1_000_000,
        suggested_max_tokens=64_000,
        capabilities=Capabilities(text=True, image=True, video=True),
    ),
    "qwen3.7-plus-2026-05-26": QwenModelEntry(
        id="qwen3.7-plus-2026-05-26",
        name="Qwen3.7 Plus 2026-05-26",
        description="Qwen3.7 Plus 快照版本，1M 超长上下文，支持图像与视频理解。",
        context_window=1_000_000,
        suggested_max_tokens=64_000,
        capabilities=Capabilities(text=True, image=True, video=True),
    ),
    "qwen-vl-max-0319": QwenModelEntry(
        id="qwen-vl-max-0319",
        name="Qwen VL Max 0319",
        description="最新视觉语言模型，支持图像、视频理解",
        context_window=131_072,
        suggested_max_tokens=8_192,
        capabilities=Capabilities(text=True, image=True, video=True),
    ),
    "qwen-plus-0419": QwenModelEntry(
        id="qwen-plus-0419",
        name="Qwen Plus 0419",
        description="最新文本主力模型，长上下文",
        context_window=1_000_000,
        suggested_max_tokens=16_384,
        capabilities=Capabilities(text=True),
        recommended=True,
    ),
    "qwen-turbo-0419": QwenModelEntry(
        id="qwen-turbo-0419",
        name="Qwen Turbo 0419",
        description="最新轻量文本模型，响应极快",
        context_window=1_000_000,
        suggested_max_tokens=4_096,
        capabilities=Capabilities(text=True),
    ),
    "qwen2.5-72b-instruct": QwenModelEntry(
        id="qwen2.5-72b-instruct",
        name="Qwen2.5 72B Instruct",
        description="Qwen2.5 系列 72B 文本模型，适合大规模文本生成。",
        context_window=128_000,
        suggested_max_tokens=8_192,
        capabilities=Capabilities(text=True),
    ),
    "qwen2.5-32b-instruct": QwenModelEntry(
        id="qwen2.5-32b-instruct",
        name="Qwen2.5 32B Instruct",
        description="Qwen2.5 系列 32B 文本模型，三十二亿参数均衡之选。",
        context_window=128_000,
        suggested_max_tokens=8_192,
        capabilities=Capabilities(text=True),
    ),
    "qwen2.5-14b-instruct": QwenModelEntry(
        id="qwen2.5-14b-instruct",
        name="Qwen2.5 14B Instruct",
        description="Qwen2.5 系列 14B 文本模型，轻量部署首选。",
        context_window=128_000,
        suggested_max_tokens=8_192,
        capabilities=Capabilities(text=True),
    ),
}
