"""OpenAI-compatible provider model catalog entries."""

from __future__ import annotations

from .schemas import Capabilities, QwenModelEntry

COMPATIBLE_MODELS: dict[str, QwenModelEntry] = {
    "gpt-4o": QwenModelEntry(
        id="gpt-4o",
        name="GPT-4o",
        description="OpenAI 最新多模态旗舰模型，支持图片、音频输入",
        context_window=128_000,
        suggested_max_tokens=16_384,
        capabilities=Capabilities(text=True, image=True, audio=True),
        recommended=True,
    ),
    "gpt-4o-mini": QwenModelEntry(
        id="gpt-4o-mini",
        name="GPT-4o Mini",
        description="GPT-4o 轻量版，性价比优秀，适合日常任务",
        context_window=128_000,
        suggested_max_tokens=16_384,
        capabilities=Capabilities(text=True, image=True),
    ),
    "gpt-4-turbo": QwenModelEntry(
        id="gpt-4-turbo",
        name="GPT-4 Turbo",
        description="OpenAI GPT-4 Turbo 模型，支持 128K 上下文",
        context_window=128_000,
        suggested_max_tokens=4_096,
        capabilities=Capabilities(text=True),
    ),
    "o1": QwenModelEntry(
        id="o1",
        name="o1",
        description="OpenAI o1 推理模型，擅长复杂数学、科学推理",
        context_window=200_000,
        suggested_max_tokens=100_000,
        capabilities=Capabilities(text=True),
    ),
    "o3-mini": QwenModelEntry(
        id="o3-mini",
        name="o3 Mini",
        description="OpenAI o3 轻量推理模型，支持可调推理努力",
        context_window=200_000,
        suggested_max_tokens=100_000,
        capabilities=Capabilities(text=True),
    ),
    "deepseek-chat": QwenModelEntry(
        id="deepseek-chat",
        name="DeepSeek Chat",
        description="DeepSeek V4 对话模型，支持 1M 上下文窗口",
        context_window=1_000_000,
        suggested_max_tokens=8_192,
        capabilities=Capabilities(text=True),
    ),
    "deepseek-reasoner": QwenModelEntry(
        id="deepseek-reasoner",
        name="DeepSeek Reasoner",
        description="DeepSeek R1 推理模型，擅长复杂推理任务",
        context_window=1_000_000,
        suggested_max_tokens=8_192,
        capabilities=Capabilities(text=True),
    ),
    "deepseek-v3": QwenModelEntry(
        id="deepseek-v3",
        name="DeepSeek V3",
        description="DeepSeek V3 对话模型，支持 1M 上下文窗口",
        context_window=1_000_000,
        suggested_max_tokens=8_192,
        capabilities=Capabilities(text=True),
    ),
    "deepseek-r1": QwenModelEntry(
        id="deepseek-r1",
        name="DeepSeek R1",
        description="DeepSeek R1 推理模型，擅长复杂数学、逻辑推理",
        context_window=1_000_000,
        suggested_max_tokens=8_192,
        capabilities=Capabilities(text=True),
    ),
    "deepseek-v4-flash": QwenModelEntry(
        id="deepseek-v4-flash",
        name="DeepSeek V4 Flash",
        description="DeepSeek V4 高速对话模型，1M 上下文窗口，低延迟高吞吐。",
        context_window=1_000_000,
        suggested_max_tokens=8_192,
        capabilities=Capabilities(text=True),
    ),
    "deepseek-v4-pro": QwenModelEntry(
        id="deepseek-v4-pro",
        name="DeepSeek V4 Pro",
        description="DeepSeek V4 专业版，更强推理能力，1M 上下文窗口。",
        context_window=1_000_000,
        suggested_max_tokens=8_192,
        capabilities=Capabilities(text=True),
    ),
    "moonshot-v1-8k": QwenModelEntry(
        id="moonshot-v1-8k",
        name="Moonshot V1 8K",
        description="月之暗面 Kimi 模型，8K 上下文版本",
        context_window=8_192,
        suggested_max_tokens=4_096,
        capabilities=Capabilities(text=True),
    ),
    "moonshot-v1-32k": QwenModelEntry(
        id="moonshot-v1-32k",
        name="Moonshot V1 32K",
        description="月之暗面 Kimi 模型，32K 上下文版本",
        context_window=32_768,
        suggested_max_tokens=8_192,
        capabilities=Capabilities(text=True),
    ),
    "moonshot-v1-128k": QwenModelEntry(
        id="moonshot-v1-128k",
        name="Moonshot V1 128K",
        description="月之暗面 Kimi 模型，128K 上下文版本，适合长文档分析",
        context_window=131_072,
        suggested_max_tokens=8_192,
        capabilities=Capabilities(text=True),
    ),
    "glm-4-plus": QwenModelEntry(
        id="glm-4-plus",
        name="GLM-4 Plus",
        description="智谱 AI GLM-4 旗舰模型，支持 128K 上下文",
        context_window=128_000,
        suggested_max_tokens=8_192,
        capabilities=Capabilities(text=True),
    ),
    "glm-4-flash": QwenModelEntry(
        id="glm-4-flash",
        name="GLM-4 Flash",
        description="智谱 AI GLM-4 轻量快速模型，响应速度快",
        context_window=128_000,
        suggested_max_tokens=4_096,
        capabilities=Capabilities(text=True),
    ),
    "glm-4v-plus": QwenModelEntry(
        id="glm-4v-plus",
        name="GLM-4V Plus",
        description="智谱 AI GLM-4V 多模态模型，支持图片理解",
        context_window=128_000,
        suggested_max_tokens=4_096,
        capabilities=Capabilities(text=True, image=True),
    ),
    "baichuan4": QwenModelEntry(
        id="baichuan4",
        name="百川4",
        description="百川智能最新旗舰模型，支持 32K 上下文",
        context_window=32_768,
        suggested_max_tokens=4_096,
        capabilities=Capabilities(text=True),
    ),
    "baichuan3-turbo": QwenModelEntry(
        id="baichuan3-turbo",
        name="百川3 Turbo",
        description="百川智能轻量快速模型，适合日常对话",
        context_window=32_768,
        suggested_max_tokens=4_096,
        capabilities=Capabilities(text=True),
    ),
    # ── OpenAI GPT-4.1 Series (2025-04) ──────────────────────────────────
    "gpt-4.1": QwenModelEntry(
        id="gpt-4.1",
        name="GPT-4.1",
        description="OpenAI GPT-4.1 旗舰模型，1M 上下文，支持图片输入与结构化输出",
        context_window=1_047_576,
        suggested_max_tokens=32_768,
        capabilities=Capabilities(text=True, image=True),
        recommended=True,
    ),
    "gpt-4.1-mini": QwenModelEntry(
        id="gpt-4.1-mini",
        name="GPT-4.1 Mini",
        description="GPT-4.1 轻量版，1M 上下文，性价比优秀",
        context_window=1_047_576,
        suggested_max_tokens=32_768,
        capabilities=Capabilities(text=True, image=True),
    ),
    "gpt-4.1-nano": QwenModelEntry(
        id="gpt-4.1-nano",
        name="GPT-4.1 Nano",
        description="GPT-4.1 极速版，1M 上下文，最低延迟与成本",
        context_window=1_047_576,
        suggested_max_tokens=32_768,
        capabilities=Capabilities(text=True, image=True),
    ),
    # ── OpenAI o Series (2025) ───────────────────────────────────────────
    "o3": QwenModelEntry(
        id="o3",
        name="o3",
        description="OpenAI o3 推理模型，增强推理能力，支持图片与工具调用",
        context_window=200_000,
        suggested_max_tokens=100_000,
        capabilities=Capabilities(text=True, image=True),
    ),
    "o4-mini": QwenModelEntry(
        id="o4-mini",
        name="o4 Mini",
        description="OpenAI o4 轻量推理模型，增强推理，支持图片与结构化输出",
        context_window=200_000,
        suggested_max_tokens=100_000,
        capabilities=Capabilities(text=True, image=True),
    ),
    # ── OpenAI GPT-5 Series (2025-08) ────────────────────────────────────
    "gpt-5": QwenModelEntry(
        id="gpt-5",
        name="GPT-5",
        description="OpenAI GPT-5 旗舰推理模型，400K 上下文，支持图片与工具调用",
        context_window=400_000,
        suggested_max_tokens=128_000,
        capabilities=Capabilities(text=True, image=True),
        recommended=True,
    ),
    "gpt-5-mini": QwenModelEntry(
        id="gpt-5-mini",
        name="GPT-5 Mini",
        description="GPT-5 轻量版，400K 上下文，推理与多模态兼顾",
        context_window=400_000,
        suggested_max_tokens=128_000,
        capabilities=Capabilities(text=True, image=True),
    ),
    "gpt-5-nano": QwenModelEntry(
        id="gpt-5-nano",
        name="GPT-5 Nano",
        description="GPT-5 极速版，400K 上下文，最低成本推理",
        context_window=400_000,
        suggested_max_tokens=128_000,
        capabilities=Capabilities(text=True, image=True),
    ),
    # ── Anthropic Claude (2025-2026) ─────────────────────────────────────
    "claude-opus-4-20250514": QwenModelEntry(
        id="claude-opus-4-20250514",
        name="Claude Opus 4",
        description="Anthropic 最强旗舰模型，200K 上下文，擅长复杂推理与编码",
        context_window=200_000,
        suggested_max_tokens=32_768,
        capabilities=Capabilities(text=True, image=True),
        recommended=True,
    ),
    "claude-sonnet-4-20250514": QwenModelEntry(
        id="claude-sonnet-4-20250514",
        name="Claude Sonnet 4",
        description="Anthropic Claude Sonnet 4，200K 上下文，平衡性能与速度",
        context_window=200_000,
        suggested_max_tokens=64_000,
        capabilities=Capabilities(text=True, image=True),
    ),
    "claude-3-5-haiku-20241022": QwenModelEntry(
        id="claude-3-5-haiku-20241022",
        name="Claude 3.5 Haiku",
        description="Anthropic 轻量快速模型，200K 上下文，低延迟高吞吐",
        context_window=200_000,
        suggested_max_tokens=8_192,
        capabilities=Capabilities(text=True, image=True),
    ),
    # ── Google Gemini 2.5 (2025) ─────────────────────────────────────────
    "gemini-2.5-pro": QwenModelEntry(
        id="gemini-2.5-pro",
        name="Gemini 2.5 Pro",
        description="Google 旗舰多模态模型，1M 上下文，支持思考与工具调用",
        context_window=1_048_576,
        suggested_max_tokens=65_536,
        capabilities=Capabilities(text=True, image=True, video=True, audio=True),
        recommended=True,
    ),
    "gemini-2.5-flash": QwenModelEntry(
        id="gemini-2.5-flash",
        name="Gemini 2.5 Flash",
        description="Google 高速多模态模型，1M 上下文，支持思考与工具调用",
        context_window=1_048_576,
        suggested_max_tokens=65_536,
        capabilities=Capabilities(text=True, image=True, video=True, audio=True),
    ),
    # ── xAI Grok (2025-2026) ─────────────────────────────────────────────
    "grok-4": QwenModelEntry(
        id="grok-4",
        name="Grok 4",
        description="xAI Grok 4 推理模型，262K 上下文，支持工具调用",
        context_window=262_000,
        suggested_max_tokens=8_192,
        capabilities=Capabilities(text=True),
    ),
    "grok-4.1-fast-reasoning": QwenModelEntry(
        id="grok-4.1-fast-reasoning",
        name="Grok 4.1 Fast",
        description="xAI Grok 4.1 高速推理模型，128K 上下文，支持图片输入",
        context_window=128_000,
        suggested_max_tokens=128_000,
        capabilities=Capabilities(text=True, image=True),
    ),
    # ── Moonshot Kimi K2 (2025-2026) ─────────────────────────────────────
    "kimi-k2.5": QwenModelEntry(
        id="kimi-k2.5",
        name="Kimi K2.5",
        description="月之暗面 Kimi K2.5 多模态推理模型，262K 上下文，支持工具调用",
        context_window=262_144,
        suggested_max_tokens=262_144,
        capabilities=Capabilities(text=True, image=True),
    ),
    "kimi-k2.6": QwenModelEntry(
        id="kimi-k2.6",
        name="Kimi K2.6",
        description="月之暗面 Kimi K2.6 多模态推理模型，262K 上下文，支持工具调用",
        context_window=262_144,
        suggested_max_tokens=262_144,
        capabilities=Capabilities(text=True, image=True),
    ),
    "kimi-k2.7-code": QwenModelEntry(
        id="kimi-k2.7-code",
        name="Kimi K2.7 Code",
        description="月之暗面 Kimi K2.7 代码推理模型，262K 上下文，支持工具调用",
        context_window=262_144,
        suggested_max_tokens=262_144,
        capabilities=Capabilities(text=True, image=True),
    ),
    # ── DeepSeek V3.2 (2026) ─────────────────────────────────────────────
    "deepseek-v3.2": QwenModelEntry(
        id="deepseek-v3.2",
        name="DeepSeek V3.2",
        description="DeepSeek V3.2 对话模型，128K 上下文，支持推理内容",
        context_window=128_000,
        suggested_max_tokens=128_000,
        capabilities=Capabilities(text=True),
    ),
    "deepseek-v3.2-speciale": QwenModelEntry(
        id="deepseek-v3.2-speciale",
        name="DeepSeek V3.2 Speciale",
        description="DeepSeek V3.2 特别版，128K 上下文，增强推理",
        context_window=128_000,
        suggested_max_tokens=128_000,
        capabilities=Capabilities(text=True),
    ),
    # ── Mistral AI (2025-2026) ───────────────────────────────────────────
    "mistral-large-latest": QwenModelEntry(
        id="mistral-large-latest",
        name="Mistral Large 3",
        description="Mistral AI 旗舰模型，128K 上下文，支持多语言与工具调用",
        context_window=128_000,
        suggested_max_tokens=8_192,
        capabilities=Capabilities(text=True, image=True),
    ),
    "mistral-medium-3.5": QwenModelEntry(
        id="mistral-medium-3.5",
        name="Mistral Medium 3.5",
        description="Mistral AI 中端模型，128K 上下文，支持图片输入",
        context_window=128_000,
        suggested_max_tokens=128_000,
        capabilities=Capabilities(text=True, image=True),
    ),
    # ── Meta Llama (2025) ────────────────────────────────────────────────
    "llama-4-maverick-17b-128e-instruct": QwenModelEntry(
        id="llama-4-maverick-17b-128e-instruct",
        name="Llama 4 Maverick",
        description="Meta Llama 4 Maverick MoE 模型，1M 上下文，支持图片输入",
        context_window=1_000_000,
        suggested_max_tokens=8_192,
        capabilities=Capabilities(text=True, image=True),
    ),
    "llama-3.3-70b-instruct": QwenModelEntry(
        id="llama-3.3-70b-instruct",
        name="Llama 3.3 70B",
        description="Meta Llama 3.3 70B 指令模型，128K 上下文，多语言支持",
        context_window=128_000,
        suggested_max_tokens=8_192,
        capabilities=Capabilities(text=True),
    ),
}
