"""OpenAI-compatible provider model catalog entries."""

from __future__ import annotations

from .schemas import Capabilities, QwenModelEntry

COMPATIBLE_MODELS: dict[str, QwenModelEntry] = {
    "gpt-4o": QwenModelEntry(
        id="gpt-4o",
        name="GPT-4o",
        description="OpenAI 最新多模态旗舰模型，支持图片、音频输入",
        context_window=128_000,
        suggested_max_tokens=16_384,
        capabilities=Capabilities(text=True, image=True, audio=True),
        recommended=True,
    ),
    "gpt-4o-mini": QwenModelEntry(
        id="gpt-4o-mini",
        name="GPT-4o Mini",
        description="GPT-4o 轻量版，性价比优秀，适合日常任务",
        context_window=128_000,
        suggested_max_tokens=16_384,
        capabilities=Capabilities(text=True, image=True),
    ),
    "gpt-4-turbo": QwenModelEntry(
        id="gpt-4-turbo",
        name="GPT-4 Turbo",
        description="OpenAI GPT-4 Turbo 模型，支持 128K 上下文",
        context_window=128_000,
        suggested_max_tokens=4_096,
        capabilities=Capabilities(text=True),
    ),
    "o1": QwenModelEntry(
        id="o1",
        name="o1",
        description="OpenAI o1 推理模型，擅长复杂数学、科学推理",
        context_window=200_000,
        suggested_max_tokens=100_000,
        capabilities=Capabilities(text=True),
    ),
    "o3-mini": QwenModelEntry(
        id="o3-mini",
        name="o3 Mini",
        description="OpenAI o3 轻量推理模型，支持可调推理努力",
        context_window=200_000,
        suggested_max_tokens=100_000,
        capabilities=Capabilities(text=True),
    ),
    "deepseek-chat": QwenModelEntry(
        id="deepseek-chat",
        name="DeepSeek Chat",
        description="DeepSeek V4 对话模型，支持 1M 上下文窗口",
        context_window=1_000_000,
        suggested_max_tokens=8_192,
        capabilities=Capabilities(text=True),
    ),
    "deepseek-reasoner": QwenModelEntry(
        id="deepseek-reasoner",
        name="DeepSeek Reasoner",
        description="DeepSeek R1 推理模型，擅长复杂推理任务",
        context_window=1_000_000,
        suggested_max_tokens=8_192,
        capabilities=Capabilities(text=True),
    ),
    "deepseek-v3": QwenModelEntry(
        id="deepseek-v3",
        name="DeepSeek V3",
        description="DeepSeek V3 对话模型，支持 1M 上下文窗口",
        context_window=1_000_000,
        suggested_max_tokens=8_192,
        capabilities=Capabilities(text=True),
    ),
    "deepseek-r1": QwenModelEntry(
        id="deepseek-r1",
        name="DeepSeek R1",
        description="DeepSeek R1 推理模型，擅长复杂数学、逻辑推理",
        context_window=1_000_000,
        suggested_max_tokens=8_192,
        capabilities=Capabilities(text=True),
    ),
    "deepseek-v4-flash": QwenModelEntry(
        id="deepseek-v4-flash",
        name="DeepSeek V4 Flash",
        description="DeepSeek V4 高速对话模型，1M 上下文窗口，低延迟高吞吐。",
        context_window=1_000_000,
        suggested_max_tokens=8_192,
        capabilities=Capabilities(text=True),
    ),
    "deepseek-v4-pro": QwenModelEntry(
        id="deepseek-v4-pro",
        name="DeepSeek V4 Pro",
        description="DeepSeek V4 专业版，更强推理能力，1M 上下文窗口。",
        context_window=1_000_000,
        suggested_max_tokens=8_192,
        capabilities=Capabilities(text=True),
    ),
    "moonshot-v1-8k": QwenModelEntry(
        id="moonshot-v1-8k",
        name="Moonshot V1 8K",
        description="月之暗面 Kimi 模型，8K 上下文版本",
        context_window=8_192,
        suggested_max_tokens=4_096,
        capabilities=Capabilities(text=True),
    ),
    "moonshot-v1-32k": QwenModelEntry(
        id="moonshot-v1-32k",
        name="Moonshot V1 32K",
        description="月之暗面 Kimi 模型，32K 上下文版本",
        context_window=32_768,
        suggested_max_tokens=8_192,
        capabilities=Capabilities(text=True),
    ),
    "moonshot-v1-128k": QwenModelEntry(
        id="moonshot-v1-128k",
        name="Moonshot V1 128K",
        description="月之暗面 Kimi 模型，128K 上下文版本，适合长文档分析",
        context_window=131_072,
        suggested_max_tokens=8_192,
        capabilities=Capabilities(text=True),
    ),
    "glm-4-plus": QwenModelEntry(
        id="glm-4-plus",
        name="GLM-4 Plus",
        description="智谱 AI GLM-4 旗舰模型，支持 128K 上下文",
        context_window=128_000,
        suggested_max_tokens=8_192,
        capabilities=Capabilities(text=True),
    ),
    "glm-4-flash": QwenModelEntry(
        id="glm-4-flash",
        name="GLM-4 Flash",
        description="智谱 AI GLM-4 轻量快速模型，响应速度快",
        context_window=128_000,
        suggested_max_tokens=4_096,
        capabilities=Capabilities(text=True),
    ),
    "glm-4v-plus": QwenModelEntry(
        id="glm-4v-plus",
        name="GLM-4V Plus",
        description="智谱 AI GLM-4V 多模态模型，支持图片理解",
        context_window=128_000,
        suggested_max_tokens=4_096,
        capabilities=Capabilities(text=True, image=True),
    ),
    "baichuan4": QwenModelEntry(
        id="baichuan4",
        name="百川4",
        description="百川智能最新旗舰模型，支持 32K 上下文",
        context_window=32_768,
        suggested_max_tokens=4_096,
        capabilities=Capabilities(text=True),
    ),
    "baichuan3-turbo": QwenModelEntry(
        id="baichuan3-turbo",
        name="百川3 Turbo",
        description="百川智能轻量快速模型，适合日常对话",
        context_window=32_768,
        suggested_max_tokens=4_096,
        capabilities=Capabilities(text=True),
    ),
}
